export const demo = {
  state: {
    gameOrder: [
      'RyIShgbZguXIWlp2xuyPXqSmRUT2',
      '7bwydsYi6WVfc4oCdugENiBJrcq1',
      'YKj56X0vMAUYUgVn9AEZOS0zAJU2',
    ],
    roundGoods: ['good-189', 'good-103', 'good-78', 'good-120', 'good-165', 'good-61', 'good-44'],
    round: {
      current: 5,
      total: 5,
    },
    supervisorId: '7bwydsYi6WVfc4oCdugENiBJrcq1',
    bossIdea: {
      id: 'ONE_WORD',
      type: 'communication',
      title: {
        en: 'Provisional measure: Silence',
        pt: 'Medida provisória: Silêncio',
      },
      subtitle: {
        pt: 'Conversa fiada faz mal ao trabalho!',
        en: 'Chit-chat is bad for work!',
      },
      description: {
        en: 'Each worker can only say one word for each good. You may repeat that word',
        pt: 'Cada trabalhador só pode dizer uma palavra para cada mercadoria. Você pode repetir essa palavra',
      },
      og: 'Could have been an email',
      difficulty: 3,
    },
    stocked: 34,
    phase: 'GOOD_PLACEMENT',
    goodsDict: {
      'good-104': {
        id: 'good-104',
        slot: null,
        exposed: false,
      },
      'good-109': {
        id: 'good-109',
        slot: null,
        exposed: false,
      },
      'good-145': {
        id: 'good-145',
        slot: null,
        exposed: false,
      },
      'good-105': {
        id: 'good-105',
        slot: null,
        exposed: false,
      },
      'good-235': {
        id: 'good-235',
        slot: null,
        exposed: false,
      },
      'good-252': {
        id: 'good-252',
        slot: null,
        exposed: false,
      },
      'good-115': {
        id: 'good-115',
        slot: null,
        exposed: false,
      },
      'good-2': {
        id: 'good-2',
        slot: null,
        exposed: false,
      },
      'good-74': {
        id: 'good-74',
        slot: null,
        exposed: false,
      },
      'good-75': {
        id: 'good-75',
        slot: null,
        exposed: false,
      },
      'good-24': {
        id: 'good-24',
        slot: null,
        exposed: false,
      },
      'good-151': {
        id: 'good-151',
        slot: null,
        exposed: false,
      },
      'good-11': {
        id: 'good-11',
        slot: null,
        exposed: false,
      },
      'good-149': {
        id: 'good-149',
        slot: null,
        exposed: false,
      },
      'good-44': {
        id: 'good-44',
        slot: null,
        exposed: false,
      },
      'good-65': {
        id: 'good-65',
        exposed: false,
        slot: 24,
      },
      'good-15': {
        id: 'good-15',
        exposed: false,
        slot: 25,
      },
      'good-83': {
        id: 'good-83',
        exposed: false,
        slot: 26,
      },
      'good-20': {
        id: 'good-20',
        exposed: false,
        slot: 27,
      },
      'good-193': {
        id: 'good-193',
        exposed: false,
        slot: 18,
      },
      'good-191': {
        id: 'good-191',
        exposed: false,
        slot: 32,
      },
      'good-218': {
        id: 'good-218',
        exposed: false,
        slot: 20,
      },
      'good-175': {
        id: 'good-175',
        exposed: false,
        slot: 23,
      },
      'good-194': {
        id: 'good-194',
        exposed: false,
        slot: 13,
      },
      'good-188': {
        id: 'good-188',
        exposed: false,
        slot: 22,
      },
      'good-220': {
        id: 'good-220',
        exposed: false,
        slot: 34,
      },
      'good-249': {
        id: 'good-249',
        exposed: false,
        slot: 16,
      },
      'good-121': {
        id: 'good-121',
        exposed: false,
        slot: 6,
      },
      'good-140': {
        id: 'good-140',
        exposed: false,
        slot: 29,
      },
      'good-192': {
        id: 'good-192',
        exposed: false,
        slot: 5,
      },
      'good-128': {
        id: 'good-128',
        exposed: false,
        slot: 9,
      },
      'good-85': {
        id: 'good-85',
        exposed: false,
        slot: 12,
      },
      'good-238': {
        id: 'good-238',
        exposed: false,
        slot: 28,
      },
      'good-132': {
        id: 'good-132',
        exposed: false,
        slot: 21,
      },
      'good-161': {
        id: 'good-161',
        exposed: false,
        slot: 19,
      },
      'good-30': {
        id: 'good-30',
        exposed: false,
        slot: 30,
      },
      'good-118': {
        id: 'good-118',
        exposed: false,
        slot: 4,
      },
      'good-21': {
        id: 'good-21',
        exposed: false,
        slot: 36,
      },
      'good-50': {
        id: 'good-50',
        exposed: false,
        slot: 14,
      },
      'good-1': {
        id: 'good-1',
        exposed: false,
        slot: 7,
      },
      'good-199': {
        id: 'good-199',
        exposed: false,
        slot: 41,
      },
      'good-187': {
        id: 'good-187',
        exposed: false,
        slot: 35,
      },
      'good-139': {
        id: 'good-139',
        exposed: false,
        slot: 37,
      },
      'good-189': {
        id: 'good-189',
        exposed: false,
        slot: 2,
      },
      'good-103': {
        id: 'good-103',
        exposed: false,
        slot: 43,
      },
      'good-78': {
        id: 'good-78',
        exposed: false,
        slot: 11,
      },
      'good-120': {
        id: 'good-120',
        exposed: false,
        slot: 33,
      },
      'good-165': {
        id: 'good-165',
        exposed: false,
        slot: 39,
      },
      'good-61': {
        id: 'good-61',
        exposed: false,
        slot: 10,
      },
    },
    players: {
      '7bwydsYi6WVfc4oCdugENiBJrcq1': {
        id: '7bwydsYi6WVfc4oCdugENiBJrcq1',
        name: 'Ian',
        avatarId: '11',
        type: 'player',
        score: 0,
        updatedAt: 1727025833985,
        isGuest: false,
        ready: false,
      },
      YKj56X0vMAUYUgVn9AEZOS0zAJU2: {
        id: 'YKj56X0vMAUYUgVn9AEZOS0zAJU2',
        name: 'KavDev',
        avatarId: '0',
        type: 'player',
        score: 0,
        updatedAt: 1727025828688,
        isGuest: false,
        ready: true,
      },
      RyIShgbZguXIWlp2xuyPXqSmRUT2: {
        id: 'RyIShgbZguXIWlp2xuyPXqSmRUT2',
        name: 'Vic',
        avatarId: '36',
        type: 'player',
        score: 0,
        updatedAt: 1727025897234,
        isGuest: false,
        ready: true,
      },
    },
    roundsGoodIndex: 6,
    warehouseGrid: {
      0: {
        id: 0,
        goodId: null,
        available: true,
        temporaryName: 'A',
        orderId: null,
        status: 'idle',
      },
      1: {
        id: 1,
        goodId: null,
        available: true,
        temporaryName: 'B',
        orderId: null,
        status: 'idle',
      },
      2: {
        id: 2,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-189',
      },
      3: {
        id: 3,
        goodId: null,
        available: true,
        temporaryName: 'C',
        orderId: null,
        status: 'idle',
      },
      4: {
        id: 4,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-118',
      },
      5: {
        id: 5,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-192',
      },
      6: {
        id: 6,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-121',
      },
      7: {
        id: 7,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-1',
      },
      8: {
        id: 8,
        goodId: null,
        available: true,
        temporaryName: 'D',
        orderId: null,
        status: 'idle',
      },
      9: {
        id: 9,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-128',
      },
      10: {
        id: 10,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-61',
      },
      11: {
        id: 11,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-78',
      },
      12: {
        id: 12,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-85',
      },
      13: {
        id: 13,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-194',
      },
      14: {
        id: 14,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-50',
      },
      15: {
        id: 15,
        goodId: null,
        available: true,
        temporaryName: 'E',
        orderId: null,
        status: 'idle',
      },
      16: {
        id: 16,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-249',
      },
      17: {
        id: 17,
        goodId: null,
        available: true,
        temporaryName: 'F',
        orderId: null,
        status: 'idle',
      },
      18: {
        id: 18,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-193',
      },
      19: {
        id: 19,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-161',
      },
      20: {
        id: 20,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-218',
      },
      21: {
        id: 21,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-132',
      },
      22: {
        id: 22,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-188',
      },
      23: {
        id: 23,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-175',
      },
      24: {
        id: 24,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-65',
      },
      25: {
        id: 25,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-15',
      },
      26: {
        id: 26,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-83',
      },
      27: {
        id: 27,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-20',
      },
      28: {
        id: 28,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-238',
      },
      29: {
        id: 29,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-140',
      },
      30: {
        id: 30,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-30',
      },
      31: {
        id: 31,
        goodId: null,
        available: true,
        temporaryName: 'G',
        orderId: null,
        status: 'idle',
      },
      32: {
        id: 32,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-191',
      },
      33: {
        id: 33,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-120',
      },
      34: {
        id: 34,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-220',
      },
      35: {
        id: 35,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-187',
      },
      36: {
        id: 36,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-21',
      },
      37: {
        id: 37,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-139',
      },
      38: {
        id: 38,
        goodId: null,
        available: true,
        temporaryName: 'H',
        orderId: null,
        status: 'idle',
      },
      39: {
        id: 39,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-165',
      },
      40: {
        id: 40,
        goodId: null,
        available: true,
        temporaryName: 'I',
        orderId: null,
        status: 'idle',
      },
      41: {
        id: 41,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-199',
      },
      42: {
        id: 42,
        goodId: null,
        available: true,
        temporaryName: 'J',
        orderId: null,
        status: 'idle',
      },
      43: {
        id: 43,
        temporaryName: null,
        orderId: null,
        status: 'idle',
        available: false,
        goodId: 'good-103',
      },
      44: {
        id: 44,
        goodId: null,
        available: true,
        temporaryName: 'K',
        orderId: null,
        status: 'idle',
      },
      45: {
        id: 45,
        goodId: null,
        available: false,
        temporaryName: null,
        orderId: null,
        status: 'idle',
      },
      46: {
        id: 46,
        goodId: null,
        available: true,
        temporaryName: 'L',
        orderId: null,
        status: 'idle',
      },
      47: {
        id: 47,
        goodId: null,
        available: false,
        temporaryName: null,
        orderId: null,
        status: 'idle',
      },
      48: {
        id: 48,
        goodId: null,
        available: true,
        temporaryName: 'M',
        orderId: null,
        status: 'idle',
      },
    },
    updatedAt: 1727026703330,
  },
};
