export const UE_SO_ISSO_PHASES = {
  WORD_SELECTION: 'WORD_SELECTION',
  SUGGEST: 'SUGGEST',
  COMPARE: 'COMPARE',
  GUESS: 'GUESS',
  VERIFY_GUESS: 'VERIFY_GUESS',
  RESULT: 'RESULT',
} as const;

export const UE_SO_ISSO_ACTIONS = {
  SUBMIT_VOTES: 'SUBMIT_VOTES',
  SUBMIT_SUGGESTIONS: 'SUBMIT_SUGGESTIONS',
  SUBMIT_OUTCOME: 'SUBMIT_OUTCOME',
  VALIDATE_SUGGESTION: 'VALIDATE_SUGGESTION',
  SEND_GUESS: 'SEND_GUESS',
  SUBMIT_VALIDATION: 'SUBMIT_VALIDATION',
} as const;

export const GUESSING_DURATION = 120;
