export const ESCAPE_ROOM_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  EPISODE_SELECTION: 'EPISODE_SELECTION',
  MISSION: 'MISSION',
  MISSION_EVALUATION: 'MISSION_EVALUATION',
  RESULTS: 'RESULTS',
  GAME_OVER: 'GAME_OVER',
};

export const ESCAPE_ROOM_ACTIONS = {
  SUBMIT_CARD_PLAY: 'SUBMIT_CARD_PLAY',
};

export const ESCAPE_ROOM_ACHIEVEMENTS = {
  FIRST_CARD_PLAYED: 'FIRST_CARD_PLAYED',
  FIRST_COMPLETE_MISSION: 'FIRST_COMPLETE_MISSION',
  FINAL_COMPLETE_MISSION: 'FINAL_COMPLETE_MISSION',
  SUCCESSFUL_ESCAPE: 'SUCCESSFUL_ESCAPE', // All players
  FAILED_ESCAPE: 'FAILED_ESCAPE', // All players
};

export const PLAYER_COUNTS = {
  MIN: 3,
  MAX: 7,
};
