export const CONTADORES_HISTORIAS_PHASES = {
  STORY: 'STORY',
  CARD_PLAY: 'CARD_PLAY',
  VOTING: 'VOTING',
  RESOLUTION: 'RESOLUTION',
} as const;

export const CONTADORES_HISTORIAS_ACTIONS = {
  SUBMIT_STORY: 'SUBMIT_STORY',
  PLAY_CARD: 'PLAY_CARD',
  SUBMIT_VOTE: 'SUBMIT_VOTE',
} as const;
