export const TEORIA_DE_CONJUNTOS_ACTIONS = {
  SUBMIT_JUDGE: 'SUBMIT_JUDGE',
  SUBMIT_ITEM_PLACEMENT: 'SUBMIT_ITEM_PLACEMENT',
  SUBMIT_EVALUATION: 'SUBMIT_EVALUATION',
  SUBMIT_EVALUATION_FIX: 'SUBMIT_EVALUATION_FIX',
} as const;

export const OUTCOME = {
  CONTINUE: 'CONTINUE',
  WRONG: 'WRONG',
  PENDING: 'PENDING',
  WIN: 'WIN',
} as const;
