// Internal
import type { DailyEspionagemEntry } from './types';

export const DEMO: DailyEspionagemEntry[] = [
  {
    id: 'demo-01',
    type: 'espionagem',
    number: 0,
    isNsfw: false,
    culpritId: 'us-gb-49',
    statements: [
      {
        key: 'testimony.t-219-pt',
        text: 'O(a) suspeito(a) tem decoração em casa do tipo "Sorrir, Viver, Amar"',
        excludes: [
          'us-gb-84',
          'us-gb-40',
          'us-gb-112',
          'us-gb-81',
          'us-gb-30',
          'us-gb-58',
          'us-gb-86',
          'us-gb-44',
        ],
      },
      {
        key: 'not.feature.male',
        text: 'O(a) suspeito(a) não é homem',
        excludes: ['us-gb-84', 'us-gb-112', 'us-gb-81', 'us-gb-30', 'us-gb-58', 'us-gb-44'],
      },
      {
        key: 'not.feature.brownHair',
        text: 'O(a) suspeito(a) não tem cabelo castanho',
        excludes: ['us-gb-84', 'us-gb-58', 'us-gb-112'],
      },
      {
        key: 'not.grid.column2',
        text: 'O(a) suspeito(a) não está na segunda coluna',
        excludes: ['us-gb-86', 'us-gb-58', 'us-gb-40'],
      },
      {
        key: 'not.feature.tie',
        text: 'O(a) suspeito(a) não está usando uma gravata',
        excludes: ['us-gb-30', 'us-gb-58', 'us-gb-81'],
      },
    ],
    suspects: [
      {
        id: 'us-gb-30',
        name: {
          en: 'Hector D.',
          pt: 'Heitor D.',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '40-50',
        height: 'tall',
        build: 'average',
        features: ['blondeHair', 'shortHair', 'tie'],
      },
      {
        id: 'us-gb-86',
        name: {
          en: 'Hariko H',
          pt: 'Hariko H',
        },
        gender: 'female',
        ethnicity: 'asian',
        age: '21-30',
        height: 'short',
        build: 'thin',
        features: ['blackHair', 'earrings', 'longHair'],
      },
      {
        id: 'us-gb-84',
        name: {
          en: 'Doug F',
          pt: 'Douglas F',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '30-40',
        height: 'medium',
        build: 'average',
        features: ['brownHair', 'shortHair', 'beard'],
      },
      {
        id: 'us-gb-44',
        name: {
          en: 'Roy R.',
          pt: 'Rômulo R.',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '50-60',
        height: 'medium',
        build: 'average',
        features: ['shortHair', 'greyHair', 'beard', 'glasses'],
      },
      {
        id: 'us-gb-58',
        name: {
          en: 'Francis F.',
          pt: 'Francisco F.',
        },
        gender: 'male',
        ethnicity: 'black',
        age: '50-60',
        height: 'tall',
        build: 'average',
        features: ['shortHair', 'brownHair', 'mustache', 'hat', 'tie'],
      },
      {
        id: 'us-gb-112',
        name: {
          en: 'Nolan H',
          pt: 'Nestor H',
        },
        gender: 'male',
        ethnicity: 'black',
        age: '50-60',
        height: 'tall',
        build: 'thin',
        features: ['hat', 'brownHair', 'longHair', 'goatee', 'mustache'],
      },
      {
        id: 'us-gb-81',
        name: {
          en: 'Jean Claude C',
          pt: 'Claudimiro C',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '60-70',
        height: 'tall',
        build: 'average',
        features: ['shortHair', 'greyHair', 'tie'],
      },
      {
        id: 'us-gb-40',
        name: {
          en: 'Patricia N.',
          pt: 'Patrícia N.',
        },
        gender: 'female',
        ethnicity: 'black',
        age: '30-40',
        height: 'medium',
        build: 'large',
        features: ['lipstick', 'glasses', 'headscarf', 'scarf', 'earrings'],
      },
      {
        id: 'us-gb-49',
        name: {
          en: 'Kristen W.',
          pt: 'Cristina W.',
        },
        gender: 'female',
        ethnicity: 'caucasian',
        age: '50-60',
        height: 'short',
        build: 'thin',
        features: ['longHair', 'blondeHair', 'earrings', 'lipstick'],
      },
    ],
    reason: {
      en: 'Sent anonymous love letters laced with dangerous spores.',
      pt: 'Enviava cartas de amor anônimas com esporos perigosos.',
    },
    setId: 'us-gb-49::cr-130::testimony.t-219-pt',
    level: 1,
  },
  {
    id: 'demo-02',
    type: 'espionagem',
    number: 0,
    isNsfw: false,
    culpritId: 'us-gb-70',
    statements: [
      {
        key: 'testimony.t-93-pt',
        text: 'O(a) suspeito(a) não joga videogames',
        excludes: ['us-gb-100', 'us-gb-06'],
      },
      {
        key: 'not.feature.male',
        text: 'O(a) suspeito(a) não é homem',
        excludes: ['us-gb-61', 'us-gb-100', 'us-gb-44', 'us-gb-11', 'us-gb-06'],
      },
      {
        key: 'not.feature.lipstick',
        text: 'O(a) suspeito(a) não está usando batom',
        excludes: ['us-gb-109', 'us-gb-76', 'us-gb-13'],
      },
      {
        key: 'not.grid.column3',
        text: 'O(a) suspeito(a) não está na terceira coluna',
        excludes: ['us-gb-11', 'us-gb-76', 'us-gb-13'],
      },
      {
        key: 'not.feature.beard',
        text: 'O(a) suspeito(a) não tem barba',
        excludes: ['us-gb-61', 'us-gb-11', 'us-gb-44'],
      },
    ],
    suspects: [
      {
        id: 'us-gb-61',
        name: {
          en: 'Samuel I.',
          pt: 'Sandoval I.',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '40-50',
        height: 'tall',
        build: 'thin',
        features: ['longHair', 'blondeHair', 'beard', 'necklace', 'earrings'],
      },
      {
        id: 'us-gb-109',
        name: {
          en: 'Shirley E',
          pt: 'Shirley E',
        },
        gender: 'female',
        ethnicity: 'caucasian',
        age: '21-30',
        height: 'medium',
        build: 'thin',
        features: ['blackHair', 'hat', 'lipstick'],
      },
      {
        id: 'us-gb-11',
        name: {
          en: 'Norton K.',
          pt: 'Nelson K.',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '40-50',
        height: 'tall',
        build: 'average',
        features: ['beard', 'brownHair', 'mediumHair'],
      },
      {
        id: 'us-gb-06',
        name: {
          en: 'Fredrick F.',
          pt: 'Frederico F.',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '21-30',
        height: 'tall',
        build: 'muscular',
        features: ['blackHair', 'shortHair'],
      },
      {
        id: 'us-gb-44',
        name: {
          en: 'Roy R.',
          pt: 'Rômulo R.',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '50-60',
        height: 'medium',
        build: 'average',
        features: ['shortHair', 'greyHair', 'beard', 'glasses'],
      },
      {
        id: 'us-gb-76',
        name: {
          en: 'Abigail X',
          pt: 'Abigail X',
        },
        gender: 'female',
        ethnicity: 'caucasian',
        age: '21-30',
        height: 'short',
        build: 'large',
        features: ['blackHair', 'glasses', 'lipstick', 'earrings', 'mediumHair'],
      },
      {
        id: 'us-gb-70',
        name: {
          en: 'Deborah R.',
          pt: 'Dulce R.',
        },
        gender: 'female',
        ethnicity: 'caucasian',
        age: '80-90',
        height: 'medium',
        build: 'average',
        features: ['greyHair', 'earrings', 'headscarf'],
      },
      {
        id: 'us-gb-100',
        name: {
          en: 'Easton V',
          pt: 'Ericlécio V',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '30-40',
        height: 'short',
        build: 'thin',
        features: ['bald', 'longHair', 'brownHair', 'goatee'],
      },
      {
        id: 'us-gb-13',
        name: {
          en: 'Megan M.',
          pt: 'Marta M.',
        },
        gender: 'female',
        ethnicity: 'asian',
        age: '21-30',
        height: 'medium',
        build: 'thin',
        features: ['scarf', 'piercings', 'coloredHair', 'shortHair', 'lipstick', 'necklace'],
      },
    ],
    reason: {
      en: 'Held a press conference to deny crimes no one knew about yet.',
      pt: 'Fez uma coletiva de imprensa para negar crimes que ninguém sabia ainda.',
    },
    setId: 'us-gb-70::cr-109::testimony.t-93-pt',
    level: 3,
  },
  {
    id: 'demo-03',
    type: 'espionagem',
    number: 0,
    isNsfw: false,
    culpritId: 'us-gb-101',
    statements: [
      {
        key: 'testimony.t-55-pt',
        text: 'O(a) suspeito(a) não mora na zona sul (área rica)',
        excludes: ['us-gb-30', 'us-gb-42'],
      },
      {
        key: 'not.feature.earrings',
        text: 'O(a) suspeito(a) não está usando brincos',
        excludes: ['us-gb-42', 'us-gb-108', 'us-gb-40', 'us-gb-99', 'us-gb-64', 'us-gb-16'],
      },
      {
        key: 'not.feature.blondeHair',
        text: 'O(a) suspeito(a) não tem cabelo loiro',
        excludes: ['us-gb-23', 'us-gb-30', 'us-gb-42'],
      },
      {
        key: 'not.grid.row2',
        text: 'O(a) suspeito(a) não está na segunda linha',
        excludes: ['us-gb-23', 'us-gb-16', 'us-gb-40'],
      },
      {
        key: 'not.feature.caucasian',
        text: 'O(a) suspeito(a) não é caucasiano(a)',
        excludes: ['us-gb-23', 'us-gb-30', 'us-gb-64', 'us-gb-42'],
      },
    ],
    suspects: [
      {
        id: 'us-gb-108',
        name: {
          en: 'Clayton D',
          pt: 'Cleiton D',
        },
        gender: 'male',
        ethnicity: 'latino',
        age: '21-30',
        height: 'tall',
        build: 'average',
        features: ['earrings', 'brownHair', 'shortHair'],
      },
      {
        id: 'us-gb-101',
        name: {
          en: 'Josiah W',
          pt: 'Jaci W',
        },
        gender: 'male',
        ethnicity: 'asian',
        age: '30-40',
        height: 'medium',
        build: 'average',
        features: ['hat', 'glasses', 'shortHair', 'blackHair'],
      },
      {
        id: 'us-gb-99',
        name: {
          en: 'Vanessa U',
          pt: 'Valesca U',
        },
        gender: 'female',
        ethnicity: 'black',
        age: '21-30',
        height: 'medium',
        build: 'muscular',
        features: ['brownHair', 'shortHair', 'earrings', 'necklace'],
      },
      {
        id: 'us-gb-23',
        name: {
          en: 'Brian W.',
          pt: 'Benedito W.',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '21-30',
        height: 'tall',
        build: 'average',
        features: ['blondeHair', 'shortHair', 'beard', 'hat'],
      },
      {
        id: 'us-gb-16',
        name: {
          en: 'Prisca P.',
          pt: 'Priscila P.',
        },
        gender: 'female',
        ethnicity: 'indian',
        age: '21-30',
        height: 'short',
        build: 'thin',
        features: ['shortHair', 'blackHair', 'earrings', 'piercings', 'lipstick'],
      },
      {
        id: 'us-gb-40',
        name: {
          en: 'Patricia N.',
          pt: 'Patrícia N.',
        },
        gender: 'female',
        ethnicity: 'black',
        age: '30-40',
        height: 'medium',
        build: 'large',
        features: ['lipstick', 'glasses', 'headscarf', 'scarf', 'earrings'],
      },
      {
        id: 'us-gb-30',
        name: {
          en: 'Hector D.',
          pt: 'Heitor D.',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '40-50',
        height: 'tall',
        build: 'average',
        features: ['blondeHair', 'shortHair', 'tie'],
      },
      {
        id: 'us-gb-64',
        name: {
          en: 'Sandra L.',
          pt: 'Sandra L.',
        },
        gender: 'female',
        ethnicity: 'caucasian',
        age: '40-50',
        height: 'medium',
        build: 'large',
        features: ['longHair', 'brownHair', 'piercings', 'earrings', 'lipstick'],
      },
      {
        id: 'us-gb-42',
        name: {
          en: 'Katherine P.',
          pt: 'Catarina P.',
        },
        gender: 'female',
        ethnicity: 'caucasian',
        age: '40-50',
        height: 'medium',
        build: 'average',
        features: ['shortHair', 'blondeHair', 'lipstick', 'earrings'],
      },
    ],
    reason: {
      en: 'Applied for over 300 fake passports — under fictional character names.',
      pt: 'Solicitou mais de 300 passaportes falsos com nomes de personagens fictícios.',
    },
    setId: 'us-gb-101::cr-131::testimony.t-55-pt',
    level: 2,
  },
  {
    id: '2025-05-25',
    type: 'espionagem',
    number: 1,
    isNsfw: false,
    culpritId: 'us-gb-07',
    statements: [
      {
        key: 'testimony.t-142-pt',
        text: 'O(a) suspeito(a) é tímido',
        excludes: [
          'us-gb-67',
          'us-gb-70',
          'us-gb-68',
          'us-gb-40',
          'us-gb-80',
          'us-gb-42',
          'us-gb-04',
          'us-gb-96',
        ],
      },
      {
        key: 'not.feature.senior',
        text: 'O(a) suspeito(a) não é idoso(a)',
        excludes: ['us-gb-67', 'us-gb-70', 'us-gb-68', 'us-gb-04', 'us-gb-96'],
      },
      {
        key: 'not.feature.hat',
        text: 'O(a) suspeito(a) não está usando um chapéu',
        excludes: ['us-gb-96', 'us-gb-67'],
      },
      {
        key: 'not.grid.column2',
        text: 'O(a) suspeito(a) não está na segunda coluna',
        excludes: ['us-gb-40', 'us-gb-80', 'us-gb-68'],
      },
      {
        key: 'not.feature.black',
        text: 'O(a) suspeito(a) não é negro(a)',
        excludes: ['us-gb-40', 'us-gb-80'],
      },
    ],
    suspects: [
      {
        id: 'us-gb-42',
        name: {
          en: 'Katherine P.',
          pt: 'Catarina P.',
        },
        gender: 'female',
        ethnicity: 'caucasian',
        age: '40-50',
        height: 'medium',
        build: 'average',
        features: ['shortHair', 'blondeHair', 'lipstick', 'earrings'],
      },
      {
        id: 'us-gb-40',
        name: {
          en: 'Patricia N.',
          pt: 'Patrícia N.',
        },
        gender: 'female',
        ethnicity: 'black',
        age: '30-40',
        height: 'medium',
        build: 'large',
        features: ['lipstick', 'glasses', 'headscarf', 'scarf', 'earrings'],
      },
      {
        id: 'us-gb-07',
        name: {
          en: 'Roger G.',
          pt: 'Rogério G.',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '18-21',
        height: 'short',
        build: 'thin',
        features: ['shortHair', 'brownHair', 'glasses'],
      },
      {
        id: 'us-gb-96',
        name: {
          en: 'Stanley R',
          pt: 'Saulo R',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '50-60',
        height: 'medium',
        build: 'average',
        features: ['longHair', 'hat', 'redHair', 'beard'],
      },
      {
        id: 'us-gb-80',
        name: {
          en: 'Anisha B',
          pt: 'Ana Dayane B',
        },
        gender: 'female',
        ethnicity: 'black',
        age: '30-40',
        height: 'short',
        build: 'thin',
        features: ['brownHair', 'mediumHair'],
      },
      {
        id: 'us-gb-67',
        name: {
          en: 'Walter O.',
          pt: 'Walter O.',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '50-60',
        height: 'medium',
        build: 'large',
        features: ['goatee', 'brownHair', 'shortHair', 'hat', 'tie'],
      },
      {
        id: 'us-gb-70',
        name: {
          en: 'Deborah R.',
          pt: 'Dulce R.',
        },
        gender: 'female',
        ethnicity: 'caucasian',
        age: '80-90',
        height: 'medium',
        build: 'average',
        features: ['greyHair', 'earrings', 'headscarf'],
      },
      {
        id: 'us-gb-68',
        name: {
          en: 'Peter P.',
          pt: 'Pequi P.',
        },
        gender: 'male',
        ethnicity: 'native-american',
        age: '50-60',
        height: 'medium',
        build: 'average',
        features: ['longHair', 'blackHair', 'necklace'],
      },
      {
        id: 'us-gb-04',
        name: {
          en: 'Paul D.',
          pt: 'Paulo D.',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '50-60',
        height: 'medium',
        build: 'thin',
        features: ['greyHair', 'bald', 'mustache', 'goatee'],
      },
    ],
    reason: {
      en: 'Issued parking tickets to ghosts — and collected.',
      pt: 'Multava fantasmas por estacionamento — e recebia o pagamento.',
    },
    setId: 'us-gb-07::cr-149::testimony.t-142-pt',
    level: 2,
  },
];
