// Internal
import type { DailyEspionagemEntry } from './types';

export const DEMO: DailyEspionagemEntry[] = [
  {
    id: 'demo1',
    type: 'espionagem',
    number: 0,
    isNsfw: false,
    culpritId: 'us-gb-01',
    statements: [
      {
        key: 'testimony.t-16-pt',
        text: 'O(a) suspeito(a) não cumprimenta seus vizinhos',
        excludes: ['us-gb-17', 'us-gb-40', 'us-gb-21', 'us-gb-12'],
      },
      {
        key: 'not.feature.caucasian',
        text: 'O(a) suspeito(a) não é caucasiano(a)',
        excludes: ['us-gb-06', 'us-gb-18', 'us-gb-27', 'us-gb-04'],
      },
      {
        key: 'not.feature.female',
        text: 'O(a) suspeito(a) não é mulher',
        excludes: ['us-gb-40', 'us-gb-12', 'us-gb-21'],
      },
      {
        key: 'not.grid.column3',
        text: 'O(a) suspeito(a) não está na terceira coluna',
        excludes: ['us-gb-04', 'us-gb-06', 'us-gb-18'],
      },
      {
        key: 'not.feature.latino',
        text: 'O(a) suspeito(a) não é latino(a)',
        excludes: ['us-gb-17'],
      },
    ],
    suspects: [
      {
        id: 'us-gb-40',
        name: {
          en: 'Patricia N',
          pt: 'Patrícia N',
        },
        gender: 'female',
        ethnicity: 'black',
        age: '30-40',
        height: 'medium',
        build: 'large',
        features: ['lipstick', 'glasses', 'headscarf', 'scarf', 'earrings'],
      },
      {
        id: 'us-gb-17',
        name: {
          en: 'Flick Q',
          pt: 'Fagner Q',
        },
        gender: 'male',
        ethnicity: 'latino',
        age: '21-30',
        height: 'medium',
        build: 'large',
        features: ['brownHair', 'shortHair'],
      },
      {
        id: 'us-gb-04',
        name: {
          en: 'Paul D',
          pt: 'Paulo D',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '50-60',
        height: 'medium',
        build: 'thin',
        features: ['greyHair', 'bald', 'mustache', 'goatee'],
      },
      {
        id: 'us-gb-12',
        name: {
          en: 'Rosanne L',
          pt: 'Rosana L',
        },
        gender: 'female',
        ethnicity: 'black',
        age: '50-60',
        height: 'medium',
        build: 'large',
        features: ['longHair', 'brownHair', 'lipstick'],
      },
      {
        id: 'us-gb-27',
        name: {
          en: 'Anthony A',
          pt: 'Antônio A',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '60-70',
        height: 'short',
        build: 'average',
        features: ['bald', 'greyHair'],
      },
      {
        id: 'us-gb-06',
        name: {
          en: 'Fredrick F',
          pt: 'Frederico F',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '21-30',
        height: 'tall',
        build: 'muscular',
        features: ['blackHair', 'shortHair'],
      },
      {
        id: 'us-gb-01',
        name: {
          en: 'Arthur A',
          pt: 'Artur A',
        },
        gender: 'male',
        ethnicity: 'black',
        age: '21-30',
        height: 'tall',
        build: 'thin',
        features: ['hat', 'tie', 'glasses', 'brownHair', 'shortHair', 'beard'],
      },
      {
        id: 'us-gb-21',
        name: {
          en: 'Una U',
          pt: 'Úrsula U',
        },
        gender: 'female',
        ethnicity: 'middle-eastern',
        age: '21-30',
        height: 'short',
        build: 'large',
        features: ['headscarf'],
      },
      {
        id: 'us-gb-18',
        name: {
          en: 'Randall R',
          pt: 'Ramon R',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '60-70',
        height: 'tall',
        build: 'average',
        features: ['greyHair', 'mustache', 'shortHair', 'hat'],
      },
      {
        id: 'us-gb-12',
        name: {
          en: 'Randall R',
          pt: 'Ramon R',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '60-70',
        height: 'tall',
        build: 'average',
        features: ['greyHair', 'mustache', 'shortHair', 'hat'],
      },
      {
        id: 'us-gb-140',
        name: {
          en: 'Randall R',
          pt: 'Ramon R',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '60-70',
        height: 'tall',
        build: 'average',
        features: ['greyHair', 'mustache', 'shortHair', 'hat'],
      },
      {
        id: 'us-gb-150',
        name: {
          en: 'Randall R',
          pt: 'Ramon R',
        },
        gender: 'male',
        ethnicity: 'caucasian',
        age: '60-70',
        height: 'tall',
        build: 'average',
        features: ['greyHair', 'mustache', 'shortHair', 'hat'],
      },
    ],
    reason: {
      en: 'Filed a lawsuit against gravity — and won.',
      pt: 'Processou a gravidade — e venceu.',
    },
    setId: 'us-gb-01::cr-114::testimony.t-16-pt',
    level: 2,
    specialStatements: [],
  },
];
