export const REAL_USERS: StringDictionary = {
  JACKY: 'zrh9vmR2IMeHBQ51PPnQdKT1wm92', // jacky
  YVES: 'rxxb9ECf0mSVPNsn2BVMI96t7l32', // yves
  STEPHANIE: 'QrfLz312uQe5oPKrqD6eZWQE0Vx1', // stephanie
  MARIS: 'BPTELIfGeLXlbo7HSx3loQQyOLs2', // maris
  DRICA: 'O2IQmn3jNFdncjjoy5SEdr8AcYK2', // drica
  FLAVIA: '5CA5JhNK7dTWFJPgArU1iUdzTK53', // flavia
  PAUL: 'fhm9QYDULqawdXTaijUHyYn8Yvu1', // paul
  KAVIS: 'pK3OYEK720h9e6z8FVcZhIGfLCF3', // kavis
  PERRY: 'X020emJnxANDYqFS0bBaLwUDGoY2',
  RODRIGO: '_rodrigo',
  MARCIO: '_marcio',
  ANNA: '_anna',
  ARTHUR: '_arthur',
  TEST: '_TEST',
  BOT: '_BOT',
  MARCELO: '_marcelo',
  KUCHEN: '_kuchen',
  CHIAWEI: '3Wipb5X35IgZtK7BeBu4D17EH5q2',
};

export const USER_MAP: Record<string, string | null> = {
  '3Wipb5X35IgZtK7BeBu4D17EH5q2': 'CHIAWEI',
  '5CA5JhNK7dTWFJPgArU1iUdzTK53': 'FLAVIA',
  '90fjd4K6mhUrTcEy5U2gK40FqHN2': null,
  AlRvI1wIC7TSQZgoJez95970Nhq1: null,
  BPTELIfGeLXlbo7HSx3loQQyOLs2: 'MARIS',
  M1dpJC1rxWTqVCG0CKlNS7HS6un2: null,
  O2IQmn3jNFdncjjoy5SEdr8AcYK2: 'DRICA',
  QrfLz312uQe5oPKrqD6eZWQE0Vx1: 'STEPHANIE',
  X020emJnxANDYqFS0bBaLwUDGoY2: 'PERRY',
  XsIam47qxPfRv6TldWVoK8uMJg93: null,
  YKj56X0vMAUYUgVn9AEZOS0zAJU2: 'KAVIS',
  '_a-bot': 'BOT',
  _alex: null,
  _ankit: null,
  _anna: 'ANNA',
  _aphanie: 'STEPHANIE',
  _arthur: null,
  _arun: null,
  _asteph: 'STEPHANIE',
  '_b-bop': 'BOT',
  _bat: null,
  _chiawei: 'CHIAWEI',
  _chris: null,
  _cr7: null,
  _dan: null,
  _darthweide: null,
  _dennis: null,
  _didigo: 'RODRIGO',
  _dom: null,
  _drica: 'DRICA',
  _el_don: null,
  _fabiano: 'KAVIS',
  _fla: 'FLAVIA',
  '_fla firefo': 'TEST',
  _flavia: 'FLAVIA',
  _flaviane: 'FLAVIA',
  _francisco: null,
  _fudgebro: null,
  _glenn: null,
  _hambone: null,
  _hunter: null,
  _incognito: null,
  _irina: null,
  _it_is_blue: null,
  '_ives amor': 'TEST',
  _jacky: 'JACKY',
  _jason: null,
  _ji: null,
  _josh: null,
  _kavis: 'KAVIS',
  _kiwi: 'TEST',
  '_kuan-ying': 'KUCHEN',
  _kuchen: 'KUCHEN',
  _lucas: null,
  _luke: null,
  _magapatalo: 'STEPHANIE',
  _marcelo: null,
  _marcio: null,
  _marianag: null,
  _marianna: null,
  _maris: 'MARIS',
  _mayra: null,
  _mel: null,
  _mruganka: null,
  _nakarin: null,
  _nicolas: 'TEST',
  _noemi: null,
  _outronome: null,
  _paul: 'PAUL',
  _psycat: null,
  _radhika: null,
  _reneeh: null,
  _reptar: null,
  _roarphanie: 'STEPHANIE',
  _sathish: null,
  _shon: null,
  _snail: null,
  _spidyves: null,
  _squirrel: null,
  _stefersens: 'STEPHANIE',
  _steph: 'STEPHANIE',
  _stephvaria: 'TEST',
  _thorphanie: 'STEPHANIE',
  _veronica: null,
  _vidal: null,
  _yuin: null,
  _yves: 'YVES',
  _zack: null,
  fhm9QYDULqawdXTaijUHyYn8Yvu1: 'PAUL',
  ms8is5Vnu9dr2Ly4I6lNOk2h9xy2: 'ARTHUR',
  pK3OYEK720h9e6z8FVcZhIGfLCF3: 'KAVIS',
  rxxb9ECf0mSVPNsn2BVMI96t7l32: 'YVES',
  tWsnJQjT6ZSC6B5tjZ8dV6wPrtI3: null,
  zrh9vmR2IMeHBQ51PPnQdKT1wm92: 'JACKY',
};

export function getUserId(id: string) {
  const mapId = USER_MAP?.[id];
  if (mapId) return REAL_USERS?.[mapId] ?? id;
  return id;
}
