export const DETETIVES_IMAGINATIVOS_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  SECRET_CLUE: 'SECRET_CLUE',
  CARD_PLAY: 'CARD_PLAY',
  DEFENSE: 'DEFENSE',
  VOTING: 'VOTING',
  REVEAL: 'REVEAL',
  GAME_OVER: 'GAME_OVER',
};

export const PLAYER_COUNTS = {
  MIN: 4,
  MAX: 10,
};

export const HAND_LIMIT = 6;
