export const DETETIVES_IMAGINATIVOS_PHASES = {
  LOBBY: 'LOBBY',
  SETUP: 'SETUP',
  SECRET_CLUE: 'SECRET_CLUE',
  CARD_PLAY: 'CARD_PLAY',
  DEFENSE: 'DEFENSE',
  VOTING: 'VOTING',
  REVEAL: 'REVEAL',
  GAME_OVER: 'GAME_OVER',
} as const;

export const DETETIVES_IMAGINATIVOS_ACTIONS = {
  SUBMIT_CLUE: 'SUBMIT_CLUE',
  PLAY_CARD: 'PLAY_CARD',
  DEFEND: 'DEFEND',
  SUBMIT_VOTE: 'SUBMIT_VOTE',
} as const;

export const DETETIVES_IMAGINATIVOS_ACHIEVEMENTS = {
  MOST_LEADER: 'MOST_LEADER',
  MOST_IMPOSTOR: 'MOST_IMPOSTOR',
  LONGEST_DEFENSE: 'LONGEST_DEFENSE',
  SHORTEST_DEFENSE: 'SHORTEST_DEFENSE',
  VOTED_FOR_IMPOSTOR: 'VOTED_FOR_IMPOSTOR',
  VOTED_FOR_INNOCENT: 'VOTED_FOR_INNOCENT',
  RECEIVED_VOTES: 'RECEIVED_VOTES',
  LONGEST_CLUES: 'LONGEST_CLUES',
  SHORTEST_CLUES: 'SHORTEST_CLUES',
} as const;

export const PLAYER_COUNTS = {
  MIN: 4,
  MAX: 10,
} as const;

export const HAND_LIMIT = 8;

export const TOTAL_ROUNDS = 6;
