// Icons
import * as icons from 'icons/collection';

export const collectionByCategory: Record<string, string[]> = {
  interface: [
    'GoogleIcon',
    'VideoGameControllerIcon',
    'RotationIcon',
    'PlayerIcon',
    'PlayersIcon',
    'UserStatsIcon',
    'UsersStatsIcon',
    'RatingIcon',
    'IncreaseDifficultyIcon',
    'BellIcon',
    'NewFeatureIcon',
    'WeekendIcon',
    'RulesIcon',
  ],
  general: [
    'TDIcon',
    'RankIcon',
    'HandOfCardsIcon',
    'WaitingRoomIcon',
    'QuestionIcon',
    'QuestionsIcon',
    'ImageCardsIcon',
    'StarIcon',
    'LawIcon',
    'GarbageIcon',
    'ListIcon',
    'VerifyListIcon',
    'AnonymousIcon',
    'ThumbsUpIcon',
    'LoupeIcon',
    'PrototypeIcon',
    'AudioIcon',
    'SkipIcon',
  ],
  gameTags: [
    'CompetitiveGameIcon',
    'CooperativeGameIcon',
    'TogetherGameIcon',
    'TurnBasedGameIcon',
    'DrawingIcon',
    'WritingIcon',
    'ThinkingIcon',
    'VoteIcon',
    'EvaluateIcon',
    'CloverIcon',
    'BrainIcon',
    'TalkIcon',
    'TimerIcon',
    'TraitorIcon',
    'ImageCardsIcon',
    'GamblingChipIcon',
    'BadgeIcon',
    'RobotIcon',
    'SmartphoneIcon',
    'PuzzleIcon',
    'AudienceIcon',
    'PlayerDropIcon',
    'SoundEffectsIcon',
  ],
  inputs: ['EvaluateIcon', 'VoteIcon', 'GuessIcon', 'WritingIcon'],
  symbols: ['CheckMarkIcon', 'XIcon', 'NoIcon', 'YesIcon', 'ArrowIcon'],
  animatedTimers: [
    'AnimatedClockIcon',
    'AnimatedGearIcon',
    'AnimatedLoaderIcon',
    'AnimatedProcessingIcon',
    'AnimatedVideoConferenceIcon',
  ],
  gameOver: ['CrownIcon', 'TrophyIcon', 'TheEndIcon', 'LadderIcon', 'MedalIcon', 'FlagIcon'],
  boxes: [
    'BoxAlertIcon',
    'BoxBlankIcon',
    'BoxCheckMarkIcon',
    'BoxEqualIcon',
    'BoxMinusIcon',
    'BoxOneIcon',
    'BoxTwoIcon',
    'BoxThreeIcon',
    'BoxPlusIcon',
    'BoxQuestionMarkIcon',
    'BoxXIcon',
  ],
  userPage: ['CalendarIcon', 'CatalogIcon', 'ClockIcon', 'DiceIcon', 'MultitaskIcon'],
  daily: [
    'DailyAlienGameIcon',
    'DailyArtGameIcon',
    'DailyCrimeGameIcon',
    'DailyChildrenGameIcon',
    'DailyDrawingGameIcon',
    'DailyFindingGameIcon',
    'DailyGroupingGameIcon',
    'DailyImagesGameIcon',
    'DailyMapsGameIcon',
    'DailyMemoryGridGameIcon',
    'DailyMovieGameIcon',
    'DailyWarehouseGameIcon',
    'DailyWordGameIcon',
    'DailyDiagramGameIcon',
    'DailyContributionGameIcon',
    'DailyJudgingGameIcon',
    'DailySuspectGameIcon',
    'DailyPuzzleGameIcon',
  ],
  testPage: ['EarthIcon', 'HeartIcon'],
};

export const collectionByGame: Record<string, string[]> = {
  adedanhx: [
    'TimedWritingIcon',
    'BoxQuestionMarkIcon',
    'BoxXIcon',
    'CrownIcon',
    'ListIcon',
    'LockIcon',
    'NoIcon',
    'RankIcon',
    'SpeechBubbleThumbsDownIcon',
    'SpeechBubbleThumbsUpIcon',
    'StopIcon',
    'ThumbsUpIcon',
    'TimedWritingIcon',
    'VerifyListIcon',
    'WritingIcon',
    'XIcon',
  ],
  'arte-ruim': [
    'AnimatedLoaderIcon',
    'EvaluateIcon',
    'PaintingIcon',
    'PanicIcon',
    'PictureIcon',
    'TrophyIcon',
  ],
  'bomba-relogio': [
    'BombIcon',
    'BoxBlankIcon',
    'BuildingIcon',
    'CrownIcon',
    'PliersIcon',
    'SecurityIcon',
    'TraitorIcon',
    'WalkieTalkieIcon',
    'WireIcon',
  ],
  'colegas-de-quarto': [
    'BoxPlusIcon',
    'CashRegisterIcon',
    'CrownIcon',
    'EvaluateIcon',
    'ListIcon',
    'RatingIcon',
    'StoreIcon',
    'VerifyListIcon',
    'XIcon',
  ],
  'comunicacao-alienigena': [
    'AlienAngry2Icon',
    'AlienAngryIcon',
    'AlienCommunicationIcon',
    'AlienHappyIcon',
    'AlienNeutralIcon',
    'BooksIcon',
    'BoxCheckMarkIcon',
    'BoxMinusIcon',
    'BoxOneIcon',
    'BoxQuestionMarkIcon',
    'CheckMarkIcon',
    'ClockIcon',
    'HieroglyphIcon',
    'MagicSkullIcon',
    'OfferingIcon',
    'PlayerIcon',
    'PlayerIconsIcon',
    'QuestionIcon',
    'SkullIcon',
    'TrophyIcon',
    'UfoIcon',
  ],
  'comunicacao-duo': [
    'AlienHeartEyesIcon',
    'AlienNeutralIcon',
    'AlienStarEyesIcon',
    'MysteryBoxIcon',
    'NuclearExplosionIcon',
    'QuestionIcon',
    'TheEndIcon',
  ],
  'contadores-historias': ['FairyTaleIcon', 'ImageCardsIcon', 'SealIcon', 'TrophyIcon', 'VoteIcon'],
  'controle-de-estoque': [
    'BossIdeaIcon',
    'ClockIcon',
    'MysteryBoxIcon',
    'ShippingBoxIcon',
    'WarehouseIcon',
    'OnlineOrderIcon',
  ],
  'crimes-hediondos': [
    'AnonymousIcon',
    'BoxBlankIcon',
    'BoxCheckMarkIcon',
    'BoxMinusIcon',
    'BoxOneIcon',
    'BoxThreeIcon',
    'BoxTwoIcon',
    'BoxXIcon',
    'CardboardBoxIcon',
    'CheckMarkIcon',
    'CrimeSceneIcon',
    'CrimeTapeIcon',
    'EventIcon',
    'GuessIcon',
    'InvestigationIcon',
    'KnifeIcon',
    'LocationIcon',
    'LockIcon',
    'LoupeIcon',
    'RankIcon',
    'SkullIcon',
    'TrophyIcon',
    'XIcon',
  ],
  'cruza-palavras': ['GridIcon', 'GuessIcon', 'ListIcon', 'RankIcon', 'TrophyIcon', 'VerifyListIcon'],
  'detetives-imaginativos': [
    'AnimatedLoaderIcon',
    'DefenseIcon',
    'DisguiseIcon',
    'HangingPhotographIcon',
    'ImageCardsIcon',
    'RankIcon',
    'SecretIcon',
    'TrophyIcon',
    'VoteIcon',
  ],
  duetos: ['PuzzleIcon', 'SocksIcon', 'TrophyIcon'],
  'espiao-entre-nos': [
    'AlertIcon',
    'HandcuffsIcon',
    'LocationIcon',
    'LoupeIcon',
    'MapLocationIcon',
    'NewspaperIcon',
    'NuclearExplosionIcon',
    'OpinionsIcon',
    'PassportIcon',
    'PeopleAssessmentIcon',
    'SecretIcon',
    'SpyNewspaperIcon',
    'ThiefIcon',
    'TimerIcon',
    'TrophyIcon',
  ],
  esquiadores: [
    'GamblingChipIcon',
    'LodgeIcon',
    'QualitySealIcon',
    'QuestionIcon',
    'SealIcon',
    'SkierIcon',
    'SkiingIcon',
    'TrophyIcon',
  ],
  'fileira-de-fatos': ['BarChartIcon', 'BoxXIcon', 'FlagIcon', 'QueueIcon', 'StarIcon', 'XIcon'],
  'fofoca-quente': [
    'AgeIcon',
    'BlackmailIcon',
    'BullyingIcon',
    'CheckMarkIcon',
    'CyberBullyingIcon',
    'DetectiveIcon',
    'GenderIcon',
    'LawIcon',
    'LocationIcon',
    'PeopleAssessmentIcon',
    'PigeonIcon',
    'TeenDetectiveIcon',
  ],
  'galeria-de-sonhos': [
    'DoorSignIcon',
    'DreamIcon',
    'LadderIcon',
    'NightmareIcon',
    'RankIcon',
    'SleepIcon',
    'StarIcon',
  ],
  'idade-da-preda': [
    'BooksIcon',
    'CreateIcon',
    'EvaluateIcon',
    'PencilIcon',
    'PuzzleIcon',
    'StarIcon',
    'TrophyIcon',
  ],
  'labirinto-secreto': [
    'AnimatedProcessingIcon',
    'ArrowIcon',
    'CompassIcon',
    'DirectionsIcon',
    'FinishLineIcon',
    'FlagIcon',
    'LocationIcon',
    'MapIcon',
    'NoIcon',
    'PathIcon',
    'TreeIcon',
  ],
  'linhas-cruzadas': [
    'AnimatedLoaderIcon',
    'DrawingIcon',
    'ListIcon',
    'PhotoAlbumIcon',
    'TheEndIcon',
    'WriteIdeaIcon',
  ],
  megamix: [
    'AlienCommunicationIcon',
    'AlienIcon',
    'AnonymousIcon',
    'BikiniModelIcon',
    'BouncerIcon',
    'BoxingGlovesIcon',
    'ChoiceIcon',
    'ColorWheelIcon',
    'CrimeSceneIcon',
    'CriminalIcon',
    'CrossWordsIcon',
    'CrownIcon',
    'DJIcon',
    'DetectiveIcon',
    'DirectionsIcon',
    'DreamIcon',
    'FairyTaleIcon',
    'GarbageIcon',
    'GuessIcon',
    'KnifeIcon',
    'LoupeIcon',
    'LoveIcon',
    'MagicDoorIcon',
    'MapIcon',
    'MirrorIcon',
    'MonsterIcon',
    'MovieTheaterIcon',
    'PanicIcon',
    'PassportIcon',
    'PathIcon',
    'PictureIcon',
    'QueueIcon',
    'ReviewIcon',
    'RevolverIcon',
    'SheepIcon',
    'ShooterIcon',
    'SixPackIcon',
    'SkiingIcon',
    'SmsIcon',
    'SnowHillIcon',
    'SpeechBubbleAcceptedIcon',
    'SpeechBubbleDeclinedIcon',
    'StreetIcon',
    'TDIcon',
    'TreeOneIcon',
    'TreeThreeIcon',
    'TreeTwoIcon',
    'TrendingIcon',
    'TrickOrTreatIcon',
    'UnderConstructionIcon',
    'VIPLineIcon',
    'WavelengthDeviceIcon',
  ],
  'mente-coletiva': [
    'ArrowSignIcon',
    'CustomerReviewIcon',
    'DiscussionIcon',
    'ReviewIcon',
    'SheepIcon',
    'TheEndIcon',
    'WritingIcon',
  ],
  mesmice: [
    'ApplauseIcon',
    'BoxBlankIcon',
    'BoxCheckMarkIcon',
    'BoxEqualIcon',
    'BoxPlusIcon',
    'BoxQuestionMarkIcon',
    'BoxXIcon',
    'CheckMarkIcon',
    'CrownIcon',
    'SkullIcon',
    'ThumbsUpIcon',
    'WritingIcon',
    'XIcon',
  ],
  'medidas-nao-exatas': [
    'BarChartIcon',
    'BoxXIcon',
    'GuessIcon',
    'ListIcon',
    'QualitySealIcon',
    'SealIcon',
    'TrophyIcon',
    'XIcon',
  ],
  metalinguagem: [
    'BoxCheckMarkIcon',
    'BoxEqualIcon',
    'BoxPlusIcon',
    'BoxXIcon',
    'CheckMarkIcon',
    'CreateIcon',
    'DictionaryIcon',
    'GuessLanguageIcon',
    'SkullIcon',
    'SpeechBubbleThumbsDownIcon',
    'SpeechBubbleThumbsUpIcon',
    'ThumbsUpIcon',
    'TrophyIcon',
    'XIcon',
  ],
  'na-fila-do-banco': [
    'ActionAlertIcon',
    'AlertIcon',
    'DeckIcon',
    'DeskIcon',
    'HandOfCardsIcon',
    'TrophyIcon',
  ],
  'na-rua-do-medo': [
    'CandyIcon',
    'HouseIcon',
    'PoopIcon',
    'QuestionIcon',
    'ScaredIcon',
    'StreetIcon',
    'TabletIcon',
    'TrickOrTreatIcon',
    'WalkIcon',
  ],
  'nao-sou-robo': [
    'BadgeIcon',
    'CaptchaIcon',
    'EnergyIcon',
    'EventIcon',
    'NoIcon',
    'NuclearExplosionIcon',
    'RobotIcon',
    'SealOfApprovalIcon',
    'ThiefIcon',
    'TicketsIcon',
    'TrophyIcon',
    'UnderConstructionIcon',
    'UserStatsIcon',
  ],
  'onda-telepatica': [
    'AnimatedLoaderIcon',
    'SoundWaveIcon',
    'TrophyIcon',
    'TurbanIcon',
    'WavelengthDeviceIcon',
  ],
  'planejamento-urbano': [
    'ArrowIcon',
    'BrickWallIcon',
    'ConeIcon',
    'CrownIcon',
    'FlagIcon',
    'MapBlueprintIcon',
    'MapCityIcon',
    'MapCityZonesIcon',
    'XIcon',
  ],
  'polemica-da-vez': [
    'FeedbackIcon',
    'ReviewIcon',
    'SpeechBubbleThumbsDownIcon',
    'SpeechBubbleThumbsUpIcon',
    'TargetIcon',
    'ThumbsUpIcon',
    'TrendingIcon',
    'TrophyIcon',
    'TwitterIcon',
  ],
  'portas-dos-desesperados': [
    'DreamCatcherIcon',
    'MagicBookIcon',
    'MagicBookSpellIcon',
    'MagicCandlesIcon',
    'MagicCrystalIcon',
    'MagicCultLeaderIcon',
    'MagicDivinationIcon',
    'MagicDoorIcon',
    'MagicHamsaIcon',
    'MagicHourGlassIcon',
    'MagicRunesIcon',
    'MagicSkullIcon',
    'MagicTarotCardsIcon',
    'MagicVoodooDollIcon',
    'PanicIcon',
    'SkullIcon',
  ],
  'quem-sou-eu': [
    'BoxCheckMarkIcon',
    'CheckMarkIcon',
    'EvaluateIcon',
    'FilterIcon',
    'MirrorIcon',
    'NoIcon',
    'PlayerIcon',
    'PlayerIconsIcon',
    'TrophyIcon',
    'YesIcon',
  ],
  'qual-quesito': [
    'CrownIcon',
    'FeedbackIcon',
    'HandOfCardsIcon',
    'MysteryBoxIcon',
    'RankIcon',
    'SkipIcon',
    'SpeechBubbleAcceptedIcon',
    'SpeechBubbleDeclinedIcon',
    'WriteIdeaIcon',
  ],
  'quem-nao-mata': ['KnifeIcon', 'RevolverIcon', 'TDIcon', 'ThinkingIcon'],
  'retrato-falado': [
    'ChoiceIcon',
    'MonsterIcon',
    'QualitySealIcon',
    'SealIcon',
    'SketchIcon',
    'TimerIcon',
    'TrophyIcon',
  ],
  'senso-literario': ['BooksIcon', 'BookshelfIcon', 'CrownIcon'],
  'sinais-de-alerta': [
    'CheckMarkIcon',
    'CrownIcon',
    'DrawingIcon',
    'EvaluateIcon',
    'PanicIcon',
    'StarIcon',
    'WarningSignIcon',
  ],
  'super-campeonato': [
    'AnonymousIcon',
    'BoxingGlovesIcon',
    'GamblingChipIcon',
    'ListIcon',
    'MedalIcon',
    'ThumbsUpIcon',
    'TournamentIcon',
    'TrophyIcon',
  ],
  'ta-na-cara': [
    'AnimatedClockIcon',
    'AnonymousIcon',
    'ChatIcon',
    'ChoiceIcon',
    'ClockIcon',
    'FlagIcon',
    'SpeechBubbleAcceptedIcon',
    'SpeechBubbleDeclinedIcon',
    'SpotlightIcon',
  ],
  'teoria-de-conjuntos': [
    'ApplauseIcon',
    'ArrowIcon',
    'BoxEqualIcon',
    'CheckMarkIcon',
    'CircleIcon',
    'CrownIcon',
    'DiagramIcon',
    'GarbageIcon',
    'LawIcon',
    'SkullIcon',
    'XIcon',
  ],
  'teste-de-elenco': [
    'AgeIcon',
    'AudioIcon',
    'BrainIcon',
    'ClipboardIcon',
    'ComedyIcon',
    'CrownIcon',
    'CulturesIcon',
    'FireIcon',
    'GenderIcon',
    'KnifeIcon',
    'LoveIcon',
    'MovieActionIcon',
    'MovieComedyIcon',
    'MovieDramaIcon',
    'MovieGenreIcon',
    'MovieHorrorIcon',
    'MovieSciFiIcon',
    'MovieStarIcon',
    'NoIcon',
    'PlayerIcon',
    'RainbowIcon',
    'SkullIcon',
    'SofaIcon',
    'StarIcon',
    'SupportIcon',
  ],
  'testemunha-ocular': [
    'ClockIcon',
    'CrimeSceneIcon',
    'CriminalIcon',
    'EyeIcon',
    'InvestigationIcon',
    'LawIcon',
    'NewspaperIcon',
    'PeopleAssessmentIcon',
    'SpeechBubbleAcceptedIcon',
    'SpeechBubbleDeclinedIcon',
  ],
  'ue-so-isso': [
    'AnimatedProcessingIcon',
    'BoxBlankIcon',
    'BoxCheckMarkIcon',
    'BoxQuestionMarkIcon',
    'BoxXIcon',
    'CheckMarkIcon',
    'FlagIcon',
    'GuessIcon',
    'ListIcon',
    'OpinionsIcon',
    'SpeechBubbleIcon',
    'VerifyListIcon',
    'WritingIcon',
    'XIcon',
  ],
  'vamos-ao-cinema': [
    'FilmReelIcon',
    'FlagIcon',
    'MovieActionIcon',
    'MovieComedyIcon',
    'MovieDramaIcon',
    'MovieHorrorIcon',
    'MovieSciFiIcon',
    'MovieTheaterIcon',
    'PopcornIcon',
    'ReviewIcon',
    'ScaredIcon',
    'StarIcon',
    'TomatoIcon',
  ],
  'vendaval-de-palpites': [
    'BossIcon',
    'DiscussionIcon',
    'GarbageIcon',
    'KnowledgeIcon',
    'LoupeIcon',
    'QualitySealIcon',
    'QuestionIcon',
    'SealIcon',
    'TheEndIcon',
    'TrophyIcon',
  ],
  'vice-campeao': ['ArrowIcon', 'HandOfCardsIcon', 'NoIcon', 'TrophyIcon', 'WalkIcon'],
};

const flatGeneralList = Object.values(collectionByCategory).flat();
const flatGamesList = Object.values(collectionByGame).flat();
const flatList = [...flatGeneralList, ...flatGamesList];
export const collectionUnassigned = {
  unassigned: Object.keys(icons).filter((icon) => !flatList.includes(icon)),
};
