// Icons
import * as icons from 'icons/collection';

export const collectionByCategory: Record<string, string[]> = {
  interface: [
    'GoogleIcon',
    'VideoGameControllerIcon',
    'RotationIcon',
    'PlayerIcon',
    'PlayersIcon',
    'UserStatsIcon',
    'UsersStatsIcon',
    'RatingIcon',
  ],
  general: [
    'TDIcon',
    'RankIcon',
    'HandOfCardsIcon',
    'WaitingRoomIcon',
    'QuestionIcon',
    'QuestionsIcon',
    'ImageCardsIcon',
    'StarIcon',
    'LawIcon',
    'GarbageIcon',
    'ListIcon',
    'VerifyListIcon',
    'AnonymousIcon',
    'ThumbsUpIcon',
    'LoupeIcon',
    'PrototypeIcon',
  ],
  inputs: ['EvaluateIcon', 'VoteIcon', 'GuessIcon', 'WritingIcon'],
  symbols: ['CheckMarkIcon', 'XIcon', 'NoIcon', 'YesIcon', 'ArrowIcon'],
  animatedTimers: [
    'AnimatedClockIcon',
    'AnimatedGearIcon',
    'AnimatedLoaderIcon',
    'AnimatedProcessingIcon',
    'AnimatedVideoConferenceIcon',
  ],
  gameOver: ['CrownIcon', 'TrophyIcon', 'TheEndIcon', 'MedalIcon', 'BadgeIcon', 'LadderIcon', 'FlagIcon'],
  boxes: [
    'BoxAlertIcon',
    'BoxBlankIcon',
    'BoxCheckMarkIcon',
    'BoxEqualIcon',
    'BoxMinusIcon',
    'BoxOneIcon',
    'BoxPlusIcon',
    'BoxQuestionMarkIcon',
    'BoxXIcon',
  ],
  userPage: ['CalendarIcon', 'CatalogIcon', 'ClockIcon', 'DiceIcon'],
  daily: [
    'DailyArtGameIcon',
    'DailyCrimeGameIcon',
    'DailyDrawingGameIcon',
    'DailyFindingGameIcon',
    'DailyGroupingGameIcon',
    'DailyImagesGameIcon',
    'DailyMovieGameIcon',
    'DailyWarehouseGameIcon',
    'DailyWordGameIcon',
  ],
  testPage: ['EarthIcon', 'HeartIcon'],
};

export const collectionByGame: Record<string, string[]> = {
  adedanhx: ['TimeWritingIcon', 'LockIcon', 'StopIcon'],
  'arte-ruim': ['PaintingIcon', 'PictureIcon'],
  'comunicacao-alienigena': [
    'AlienCommunicationIcon',
    'BooksIcon',
    'HieroglyphIcon',
    'AlienAngryIcon',
    'AlienAngry2Icon',
    'AlienAngry3Icon',
    'AlienHappyIcon',
    'AlienNeutralIcon',
    'OfferingIcon',
    'UfoIcon',
  ],
  'contadores-de-historias': ['FairyTaleIcon', 'SealIcon'],
  'crimes-hediondos': [
    'EventIcon',
    'SkullIcon',
    'CrimeSceneIcon',
    'LocationIcon',
    'CrimeTapeIcon',
    'KnifeIcon',
    'CardboardBoxIcon',
  ],
  'cruza-palavras': ['GridIcon'],
  'detetives-imaginativos': ['HangingPhotographIcon', 'DefenseIcon', 'SecretIcon'],
  duetos: ['SocksIcon', 'PuzzleIcon'],
  'nao-sou-robo': [
    'CaptchaIcon',
    'EventIcon',
    'RobotIcon',
    'EnergyIcon',
    'SealOfApprovalIcon',
    'UnderConstructionIcon',
  ],
  'fileira-de-fatos': ['BarChartIcon', 'QueueIcon'],
  'galeria-de-sonhos': [
    'DoorSignIcon',
    'NightmareIcon',
    'DreamIcon',
    'SleepIcon',
    'StarIcon',
    'StarOutlineIcon',
  ],
  // mesmice: [],
  'labirinto-secreto': ['CompassIcon', 'MapIcon', 'DirectionsIcon', 'PathIcon', 'FinishLineIcon', 'TreeIcon'],
  'linhas-cruzadas': ['WriteIdeaIcon', 'PhotoAlbumIcon', 'DrawingIcon'],
  megamix: [
    'AlienIcon',
    'BikiniModelIcon',
    'BouncerIcon',
    'SixPackIcon',
    'VIPLineIcon',
    'DJIcon',
    'TreeOneIcon',
    'TreeThreeIcon',
    'TreeTwoIcon',
    'SmsIcon',
    'CrossWordsIcon',
    'DetectiveIcon',
    'ThinkingIcon',
    'ShooterIcon',
    'ColorWheelIcon',
    'RevolverIcon',
  ],
  'mente-coletiva': ['DiscussionIcon', 'SheepIcon', 'DeathIcon', 'CustomerReviewIcon', 'ArrowSignIcon'],
  'na-rua-do-medo': [
    'CandyIcon',
    'PoopIcon',
    'ScaredIcon',
    'HouseIcon',
    'StreetIcon',
    'WalkIcon',
    'TrickOrTreatIcon',
    'TabletIcon',
  ],
  'onda-telepatica': ['TurbanIcon', 'SoundWaveIcon', 'WavelengthDeviceIcon'],
  'polemica-da-vez': [
    'SpeechBubbleThumbsUpIcon',
    'SpeechBubbleThumbsDownIcon',
    'FeedbackIcon',
    'ReviewIcon',
    'TrendingIcon',
    'TargetIcon',
  ],
  'portas-dos-desesperados': [
    'MagicBookIcon',
    'MagicDoorIcon',
    'MagicCultLeaderIcon',
    'MagicSkullIcon',
    'MagicCandlesIcon',
    'MagicBookSpellIcon',
    'MagicCrystalIcon',
    'MagicDivinationIcon',
    'MagicHamsaIcon',
    'MagicHourGlassIcon',
    'MagicRunesIcon',
    'MagicTarotCardsIcon',
    'MagicVoodooDollIcon',
    'PanicIcon',
  ],
  'quem-sou-eu': ['PlayerIconsIcon', 'FilterIcon', 'MirrorIcon'],
  'retrato-falado': ['MonsterIcon', 'ChoiceIcon', 'QualitySealIcon', 'SketchIcon'],
  'sinais-de-alerta': ['WarningSignIcon'],
  'super-campeonato': ['BoxingGlovesIcon', 'GamblingChipIcon', 'TournamentIcon'],
  'teoria-de-conjuntos': ['ApplauseIcon', 'DiagramIcon', 'SkullIcon', 'CircleIcon'],
  'teste-de-elenco': [
    'SofaIcon',
    'MovieGenreIcon',
    'AgeIcon',
    'GenderIcon',
    'CulturesIcon',
    'RainbowIcon',
    'MovieStarIcon',
    'ClipboardIcon',
    'FireIcon',
    'ComedyIcon',
    'LoveIcon',
    'BrainIcon',
    'SupportIcon',
  ],
  'testemunha-ocular': [
    'EyeIcon',
    'InvestigationIcon',
    'CrimeSceneIcon',
    'CriminalIcon',
    'NewspaperIcon',
    'SpeechBubbleAcceptedIcon',
    'SpeechBubbleDeclinedIcon',
  ],
  'ue-so-isso': ['SpeechBubbleIcon', 'OpinionsIcon'],
  'vamos-ao-cinema': [
    'PopcornIcon',
    'ReviewIcon',
    'TomatoIcon',
    'ScaredIcon',
    'MovieTheaterIcon',
    'MovieActionIcon',
    'MovieComedyIcon',
    'MovieDramaIcon',
    'MovieFilmIcon',
    'MovieHorrorIcon',
    'MovieSciFiIcon',
    'FilmReelIcon',
  ],
  'vendaval-de-palpites': ['BossIcon', 'DiscussionIcon', 'KnowledgeIcon'],
  'sonhinho-bom': ['AlarmClockIcon', 'DreamCatcherIcon'],
  'espiao-entre-nos': [
    'AlertIcon',
    'SpyNewspaperIcon',
    'SecretIcon',
    'PassportIcon',
    'PeopleAssessmentIcon',
    'OpinionsIcon',
    'TimerIcon',
    'MapLocationIcon',
    'ThiefIcon',
    'NuclearExplosionIcon',
    'HandcuffsIcon',
  ],
  'bomba-relogio': ['BuildingIcon', 'PliersIcon'],
  'ta-na-cara': ['ChatIcon', 'ChoiceIcon', 'SpotlightIcon'],
  'trevo-da-sorte': ['CloverIcon'],
  'dilema-dos-esquiadores': ['SkiingIcon', 'SnowHillIcon'],
  'sonhos-pesadelos': ['CountdownIcon'],
  'controle-de-estoque': ['OnlineOrderIcon', 'ShippingBoxIcon'],
};

const flatGeneralList = Object.values(collectionByCategory).flat();
const flatGamesList = Object.values(collectionByGame).flat();
const flatList = [...flatGeneralList, ...flatGamesList];
export const collectionUnassigned = {
  unassigned: Object.keys(icons).filter((icon) => !flatList.includes(icon)),
};
