export const POLEMICA_DA_VEZ_PHASES = {
  LOBBY: 'LOBBY',
  SETUP: 'SETUP',
  TOPIC_SELECTION: 'TOPIC_SELECTION',
  REACT: 'REACT',
  RESOLUTION: 'RESOLUTION',
  GAME_OVER: 'GAME_OVER',
};

export const POLEMICA_DA_VEZ_ACTIONS = {
  SUBMIT_TOPIC: 'SUBMIT_TOPIC',
  SUBMIT_REACTION: 'SUBMIT_REACTION',
};

export const POLEMICA_DA_VEZ_ACHIEVEMENTS = {
  BIGGEST_HATER: 'BIGGEST_HATER',
  MOST_LIKER: 'MOST_LIKER',
  BEST_GUESSES: 'BEST_GUESSES',
  WORST_GUESSES: 'WORST_GUESSES',
  MOST_ONE_OFFS: 'MOST_ONE_OFFS',
  MOST_EXACTS: 'MOST_EXACTS',
};

export const PLAYER_COUNTS = {
  MIN: 3,
  MAX: 10,
};

export const SCORE_GOAL = 10;

export const MAX_ROUNDS = 15;

export const TOPICS_PER_ROUND = 4;

export const CUSTOM_TOPICS_PER_ROUND = 1;
