export const POLEMICA_DA_VEZ_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  TOPIC_SELECTION: 'TOPIC_SELECTION',
  REACT: 'REACT',
  RESOLUTION: 'RESOLUTION',
  GAME_OVER: 'GAME_OVER',
};

export const SCORE_GOAL = 4;

export const MAX_NUMBER_OF_ROUNDS = 15;

export const TOPICS_PER_ROUND = 4;

export const CUSTOM_TOPICS_PER_ROUND = 1;
