export const RETRATO_FALADO_PHASES = {
  COMPOSITE_SKETCH: 'COMPOSITE_SKETCH',
  EVALUATION: 'EVALUATION',
  REVEAL: 'REVEAL',
} as const;

export const RETRATO_FALADO_ACTIONS = {
  SUBMIT_ORIENTATION: 'SUBMIT_ORIENTATION',
  SUBMIT_SKETCH: 'SUBMIT_SKETCH',
  SUBMIT_VOTE: 'SUBMIT_VOTE',
} as const;

export const VIEWS = {
  WITNESSING: 'WITNESSING',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  SKETCHING: 'SKETCHING',
  FINISHING: 'FINISHING',
};

const MEMORY_TIME = 20;
const ANNOUNCEMENT_TIME = 5;
const SKETCH_TIME = 120;
const EXTRA_TIME = 5;

export const TIMES = {
  MEMORY: MEMORY_TIME,
  ANNOUNCEMENT: ANNOUNCEMENT_TIME,
  SKETCH: SKETCH_TIME,
  EXTRA: EXTRA_TIME,
  TOTAL: MEMORY_TIME + ANNOUNCEMENT_TIME + SKETCH_TIME + EXTRA_TIME,
  MEMORY_MARK: ANNOUNCEMENT_TIME + SKETCH_TIME + EXTRA_TIME,
  ANNOUNCEMENT_MARK: SKETCH_TIME + EXTRA_TIME,
  SKETCH_MARK: EXTRA_TIME,
};
