export const DETETIVES_IMAGINATIVOS_PHASES = {
  SECRET_CLUE: 'SECRET_CLUE',
  CARD_PLAY: 'CARD_PLAY',
  DEFENSE: 'DEFENSE',
  VOTING: 'VOTING',
  REVEAL: 'REVEAL',
} as const;

export const DETETIVES_IMAGINATIVOS_ACTIONS = {
  SUBMIT_CLUE: 'SUBMIT_CLUE',
  PLAY_CARD: 'PLAY_CARD',
  DEFEND: 'DEFEND',
  SUBMIT_VOTE: 'SUBMIT_VOTE',
} as const;
