export const TA_NA_CARA_PHASES = {
  IDENTITY_SELECTION: 'IDENTITY_SELECTION',
  PROMPTING: 'PROMPTING',
  ANSWERING: 'ANSWERING',
  GUESSING: 'GUESSING',
  REVEAL: 'REVEAL',
} as const;

export const TA_NA_CARA_ACTIONS = {
  SUBMIT_IDENTITY: 'SUBMIT_IDENTITY',
  SUBMIT_PROMPT: 'SUBMIT_PROMPT',
  SUBMIT_ANSWER: 'SUBMIT_ANSWER',
  SUBMIT_GUESSES: 'SUBMIT_GUESSES',
} as const;

export const SLIDE_DURATION = 7;
