export const TA_NA_CARA_PHASES = {
  PROMPT: 'PROMPT',
  ANSWERING: 'ANSWERING',
  GUESSING: 'GUESSING',
} as const;

export const TA_NA_CARA_ACTIONS = {
  SUBMIT_PROMPT: 'SUBMIT_PROMPT',
  SUBMIT_ANSWER: 'SUBMIT_ANSWER',
  SUBMIT_GUESS: 'SUBMIT_GUESS',
  TRIGGER_GUESSING: 'TRIGGER_GUESSING',
} as const;
