export const QUEM_NAO_MATA_PHASES = {
  TARGETING: 'TARGETING',
  STANDOFF: 'STANDOFF',
  DUEL: 'DUEL',
  RESOLUTION: 'RESOLUTION',
} as const;

export const QUEM_NAO_MATA_ACTIONS = {
  SUBMIT_TARGET: 'SUBMIT_TARGET',
  SUBMIT_MESSAGE: 'SUBMIT_MESSAGE',
  SUBMIT_DECISION: 'SUBMIT_DECISION',
} as const;
