export const TESTEMUNHA_OCULAR_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  WITNESS_SELECTION: 'WITNESS_SELECTION',
  QUESTION_SELECTION: 'QUESTION_SELECTION',
  QUESTIONING: 'QUESTIONING',
  TRIAL: 'TRIAL',
  GAME_OVER: 'GAME_OVER',
};

export const PLAYER_COUNT = {
  MIN: 2,
  MAX: 10,
};

export const MAX_ROUNDS = 11;

export const SUSPECT_COUNT = 12;

export const QUESTION_COUNT = 22;
