export const TESTEMUNHA_OCULAR_PHASES = {
  LOBBY: 'LOBBY',
  SETUP: 'SETUP',
  WITNESS_SELECTION: 'WITNESS_SELECTION',
  QUESTION_SELECTION: 'QUESTION_SELECTION',
  QUESTIONING: 'QUESTIONING',
  TRIAL: 'TRIAL',
  GAME_OVER: 'GAME_OVER',
};

export const TESTEMUNHA_OCULAR_ACTIONS = {
  SELECT_WITNESS: 'SELECT_WITNESS',
  SELECT_QUESTION: 'SELECT_QUESTION',
  GIVE_TESTIMONY: 'GIVE_TESTIMONY',
  ELIMINATE_SUSPECT: 'ELIMINATE_SUSPECT',
};

export const TESTEMUNHA_OCULAR_ACHIEVEMENTS = {
  PLAYED_AS_WITNESS: 'PLAYED_AS_WITNESS',
  BEST_QUESTIONS: 'BEST_QUESTIONS',
  MOST_USELESS_QUESTIONS: 'MOST_USELESS_QUESTIONS',
};

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 10,
};

export const MAX_ROUNDS = 10;

export const SUSPECT_COUNT = 12;

export const HARD_MODE_EXTRA_SUSPECT_COUNT = 6;

export const QUESTION_COUNT = 22;
