export const VICE_CAMPEAO_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  CARD_SELECTION: 'CARD_SELECTION',
  RUN: 'RUN',
  GAME_OVER: 'GAME_OVER',
};

export const VICE_CAMPEAO_ACTIONS = {
  SUBMIT_CARD: 'SUBMIT_CARD',
} as const;

export const VICE_CAMPEAO_ACHIEVEMENTS = {
  MOST_FIRST_PLACE: 'MOST_FIRST_PLACE',
  MOST_SECOND_PLACE: 'MOST_SECOND_PLACE',
  MOST_THIRD_PLACE: 'MOST_THIRD_PLACE',
  MOST_LAST_PLACE: 'MOST_LAST_PLACE',
  MOST_SECOND_TO_LAST_PLACE: 'MOST_SECOND_TO_LAST_PLACE',
  MOST_NO_MOVEMENT: 'MOST_NO_MOVEMENT', // ok
  MOST_SELF_CARDS: 'MOST_SELF_CARDS', // ok
  MOST_OTHER_CARDS: 'MOST_OTHER_CARDS', // ok
  MOST_MOVEMENT: 'MOST_MOVEMENT', // ok
  LEAST_MOVEMENT: 'LEAST_MOVEMENT', // ok
} as const;

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 8,
} as const;

export const MAX_ROUNDS = 5;

export const STARTING_CARDS = 2;

export const CARD_PER_ROUND = 1;
