export const ARTE_RUIM_PHASES = {
  DRAW: 'DRAW',
  EVALUATION: 'EVALUATION',
  GALLERY: 'GALLERY',
} as const;

export const ARTE_RUIM_ACTIONS = {
  SUBMIT_DRAWING: 'SUBMIT_DRAWING',
  SUBMIT_VOTING: 'SUBMIT_VOTING',
} as const;

export const SLIDE_DURATION = 10;
