export const LINHAS_CRUZADAS_PHASES = {
  SETUP: 'SETUP',
  PROMPT_SELECTION: 'PROMPT_SELECTION',
  DRAWING: 'DRAWING',
  NAMING: 'NAMING',
  PRESENTATION: 'PRESENTATION',
  GAME_OVER: 'GAME_OVER',
} as const;

export const LINHAS_CRUZADAS_ACTIONS = {
  SUBMIT_PROMPT: 'SUBMIT_PROMPT',
  SUBMIT_DRAWING: 'SUBMIT_DRAWING',
  SUBMIT_GUESS: 'SUBMIT_GUESS',
} as const;

export const TOTAL_ROUNDS = 1;

export const PLAYER_COUNTS = {
  MIN: 4,
  MAX: 10,
} as const;

export const LINHAS_CRUZADAS_ACHIEVEMENTS = {
  SLOWEST_DRAWER: 'SLOWEST_DRAWER',
  QUICKEST_DRAWER: 'QUICKEST_DRAWER',
  SLOWEST_GUESSER: 'SLOWEST_GUESSER',
  QUICKEST_GUESSER: 'QUICKEST_GUESSER',
  RANDOM_PROMPT_SELECTION: 'RANDOM_PROMPT_SELECTION',
} as const;
