export const ONDA_TELEPATICA_PHASES = {
  SETUP: 'SETUP',
  DIAL_SIDES: 'DIAL_SIDES',
  DIAL_CLUE: 'DIAL_CLUE',
  GUESS: 'GUESS',
  REVEAL: 'REVEAL',
  GAME_OVER: 'GAME_OVER',
} as const;

export const ONDA_TELEPATICA_ACTIONS = {
  SUBMIT_CATEGORY: 'SUBMIT_CATEGORY',
  SUBMIT_CLUE: 'SUBMIT_CLUE',
  SUBMIT_GUESS: 'SUBMIT_GUESS',
} as const;

export const PLAYER_COUNTS = {
  MIN: 3,
  MAX: 20,
} as const;

export const MAX_ROUNDS = 10;

export const GAME_OVER_SCORE_THRESHOLD = 10;

export const CATEGORIES_PER_ROUND = 2;

export const ONDA_TELEPATICA_ACHIEVEMENTS = {
  MOST_ACCURATE: 'MOST_ACCURATE',
  LEAST_ACCURATE: 'LEAST_ACCURATE',
  MOST_EXACT: 'MOST_EXACT',
  BEST_PSYCHIC: 'BEST_PSYCHIC',
  MOST_ZEROS: 'MOST_ZEROS',
} as const;
