export const QUEM_SOU_EU_PHASES = {
  SETUP: 'SETUP',
  CHARACTER_FILTERING: 'CHARACTER_FILTERING',
  CHARACTER_DESCRIPTION: 'CHARACTER_DESCRIPTION',
  GUESSING: 'GUESSING',
  RESULTS: 'RESULTS',
  GAME_OVER: 'GAME_OVER',
} as const;

export const QUEM_SOU_EU_ACTIONS = {
  SUBMIT_CHARACTERS: 'SUBMIT_CHARACTERS',
  SUBMIT_GLYPHS: 'SUBMIT_GLYPHS',
  SUBMIT_GUESSES: 'SUBMIT_GUESSES',
} as const;

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 10,
} as const;

export const TOTAL_ROUNDS = 5;
export const CHARACTERS_PER_PLAYER = 12;
export const GLYPHS_PER_PLAYER = 40;
export const TOTAL_GLYPHS = 365;
export const MINIMUM_CHARACTERS = 6;
export const EXTRA_CHARACTERS = 2;

export const GLYPHS_PER_ROUND = [40, 30, 20, 40, 20];
export const CHARACTERS_VISIBILITY_PER_ROUND = [true, true, true, false, false];
