export const POLEMICA_DA_VEZ_PHASES = {
  TOPIC_SELECTION: 'TOPIC_SELECTION',
  REACT: 'REACT',
  RESOLUTION: 'RESOLUTION',
} as const;

export const POLEMICA_DA_VEZ_ACTIONS = {
  SUBMIT_TOPIC: 'SUBMIT_TOPIC',
  SUBMIT_REACTION: 'SUBMIT_REACTION',
} as const;
