export const GALERIA_DE_SONHOS_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  WORD_SELECTION: 'WORD_SELECTION',
  DREAMS_SELECTION: 'DREAMS_SELECTION',
  CARD_PLAY: 'CARD_PLAY',
  RESOLUTION: 'RESOLUTION',
  GAME_OVER: 'GAME_OVER',
};

export const GALERIA_DE_SONHOS_ACTIONS = {
  SUBMIT_WORD: 'SUBMIT_WORD',
  SUBMIT_CARDS: 'SUBMIT_CARDS',
  PLAY_CARD: 'PLAY_CARD',
};

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 10,
};

export const GALERIA_DE_SONHOS_ACHIEVEMENTS = {
  MOST_MATCHES: 'MOST_MATCHES',
  MOST_FULL_MATCHES: 'MOST_FULL_MATCHES',
  FEWEST_MATCHES: 'FEWEST_MATCHES',
  MOST_VISITS: 'MOST_VISITS',
  LEAST_ADVENTUROUS: 'LEAST_ADVENTUROUS',
  MOST_ADVENTUROUS: 'MOST_ADVENTUROUS',
  MOST_PAIRS: 'MOST_PAIRS',
  MOST_OUT_OF_THE_BOX: 'MOST_OUT_OF_THE_BOX',
  MOST_LONELY: 'MOST_LONELY',
  POOREST_CHOICES: 'POOREST_CHOICES',
  SMARTEST_CHOICES: 'SMARTEST_CHOICES',
};

export const TOTAL_ROUNDS = 4;

export const TABLE_DECK_TOTAL = 30;

export const WORD_DECK_TOTAL = 7;

export const INITIAL_TABLE_SIZE = 15;
