export const PLANEJAMENTO_URBANO_ACTIONS = {
  SUBMIT_PLANNING: 'SUBMIT_PLANNING',
  UPDATE_PLACEMENT: 'UPDATE_PLACEMENT',
  SUBMIT_PLACEMENTS: 'SUBMIT_PLACEMENTS',
};

export const SLIDE_DURATION = 8;
