export const PLANEJAMENTO_URBANO_PHASES = {
  PLANNING: 'PLANNING',
  PLACING: 'PLACING',
  RESOLUTION: 'RESOLUTION',
};

export const PLANEJAMENTO_URBANO_ACTIONS = {
  SUBMIT_PLANNING: 'SUBMIT_PLANNING',
  SUBMIT_PLACEMENTS: 'SUBMIT_PLACEMENTS',
};

export const SLIDE_DURATION = 8;
