export const CRUZA_PALAVRAS_PHASES = {
  WORDS_SELECTION: 'WORDS_SELECTION',
  CLUE_WRITING: 'CLUE_WRITING',
  GUESSING: 'GUESSING',
  REVEAL: 'REVEAL',
} as const;

export const CRUZA_PALAVRAS_ACTIONS = {
  SUBMIT_WORDS: 'SUBMIT_WORDS',
  SUBMIT_CLUE: 'SUBMIT_CLUE',
  SUBMIT_GUESSES: 'SUBMIT_GUESSES',
} as const;
