export const ESCAPE_ROOM_PHASES = {
  MISSION: 'MISSION',
  MISSION_EVALUATION: 'MISSION_EVALUATION',
  RESULTS: 'RESULTS',
} as const;

export const ESCAPE_ROOM_ACTIONS = {
  SUBMIT_CARD_PLAY: 'SUBMIT_CARD_PLAY',
} as const;
