export const VENDAVAL_DE_PALPITE_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  BOSS_SELECTION: 'BOSS_SELECTION',
  SECRET_WORD_SELECTION: 'SECRET_WORD_SELECTION',
  PLAYERS_CLUES: 'PLAYERS_CLUES',
  CLUE_EVALUATIONS: 'CLUE_EVALUATIONS',
  GAME_OVER: 'GAME_OVER',
};

export const VENDAVAL_DE_PALPITE_ACTIONS = {
  SUBMIT_BOSS: 'SUBMIT_BOSS',
  SUBMIT_SECRET_WORD: 'SUBMIT_SECRET_WORD',
  SUBMIT_CLUES: 'SUBMIT_CLUES',
  SUBMIT_EVALUATION: 'SUBMIT_EVALUATION',
  SUBMIT_OUTCOME: 'SUBMIT_OUTCOME',
  SUBMIT_HELP: 'SUBMIT_HELP',
};

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 10,
};

export const MAX_ROUNDS = 7;

// The count includes the Boss
export const CLUES_PER_PLAYER = {
  2: 4,
  3: 2,
  4: 2,
  5: 1,
  6: 1,
  7: 1,
  8: 1,
  9: 1,
  10: 1,
};

export const FINAL_ANSWER_COUNT = 3;
