// Ant Design Resources
import { HeartFilled } from '@ant-design/icons';
// Components
import { Translate } from '@components/language/Translate';
// Pages
import { RulesWrapper } from '@pages/Daily/components/RulesWrapper';
// Internal
import { SETTINGS } from '../utils/settings';

type RulesProps = {
  date: string;
};

export function Rules({ date }: RulesProps) {
  return (
    <RulesWrapper
      date={date}
      basicRules={
        <>
          <li>
            <Translate
              en="You must guess which location the clues are referring to."
              pt="Você deve adivinhar qual local as dicas estão se referindo."
            />
          </li>
          <li>
            <Translate
              en="Each wrong attempt costs you a heart, but also gives you a new clue."
              pt="Cada tentativa errada você perde um coração, mas também ganha uma dica nova."
            />
          </li>
          <li>
            <Translate
              en="You also get to discover how the name of the location is formed."
              pt="Você também vai descobrindo como o nome da localização é formado."
            />
          </li>
          <li>
            <Translate
              en="All clues are generated by artificial intelligence and it's not my fault."
              pt="Todas as dicas são geradas por inteligência artificial e não são minha culpa."
            />
          </li>
          <li>
            <Translate
              en="Locations can include countries, cities, points of interest and even fictional ones."
              pt="Localizações podem incluir países, cidades, pontos de interesse e até fictícios."
            />
          </li>
          <li>
            <Translate
              en="You have {hearts} <icon/> chances. Good luck!"
              pt="Você tem {hearts} <icon/> chances. Boa sorte!"
              values={{
                hearts: SETTINGS.HEARTS,
                icon: <HeartFilled />,
              }}
            />
          </li>
        </>
      }
    />
  );
}
