// Ant Design Resources
import { HeartFilled } from '@ant-design/icons';
// Components
import { Translate } from 'components/language/Translate';
// Pages
import { RulesWrapper } from 'pages/Daily/components/RulesWrapper';
// Internal
import { SETTINGS } from '../utils/settings';

type RulesProps = {
  date: string;
};

export function Rules({ date }: RulesProps) {
  return (
    <RulesWrapper
      date={date}
      betaVersion
      basicRules={
        <Translate
          pt={
            <>
              <li>Você deve adivinhar qual local as dicas estão se referindo.</li>
              <li>Cada tentativa errada você perde um coração, mas também ganha uma dica nova.</li>
              <li>Você também vai descobrindo como o nome da localização é formado.</li>
              <li>Todas as dicas são geradas por inteligência artificial e não são minha culpa.</li>
              <li>Localizações podem incluir países, cidades, pontos de interesse e até fictícios.</li>
              <li>
                Você tem {SETTINGS.HEARTS} <HeartFilled /> chances. Boa sorte!
              </li>
            </>
          }
          en={
            <>
              <li>You must guess which location the clues are referring to.</li>
              <li>Each wrong attempt costs you a heart, but also gives you a new clue.</li>
              <li>You also get to discover how the name of the location is formed.</li>
              <li>All clues are generated by artificial intelligence and it's not my fault.</li>
              <li>Locations can include countries, cities, points of interest and even fictional ones.</li>
              <li>
                You have {SETTINGS.HEARTS} <HeartFilled /> chances. Good luck!
              </li>
            </>
          }
        />
      }
    />
  );
}
