export const NA_FILA_DO_BANCO_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  CARD_PLAY: 'CARD_PLAY',
  ROUND_RESOLUTION: 'ROUND_RESOLUTION',
  GAME_OVER: 'GAME_OVER',
};

export const NA_FILA_DO_BANCO_ACTIONS = {
  PLAY_CARD: 'PLAY_CARD',
};

export const OUTCOME = {
  SETUP: 'SETUP',
  CONTINUE: 'CONTINUE',
  END_ROUND: 'END_ROUND',
};

export const CHARACTER_TYPES = {
  RETIREE: 'RETIREE',
  VETERAN: 'VETERAN',
  MOTHER: 'MOTHER',
  BUSINESSMAN: 'BUSINESSMAN',
  STUDENT: 'STUDENT',
  MOTOBOY: 'MOTOBOY',
  KID: 'KID',
};

// What character cuts in front of what character
export const CUT_IN_HIERARCHY: Record<string, string> = {
  [CHARACTER_TYPES.RETIREE]: CHARACTER_TYPES.MOTOBOY,
  [CHARACTER_TYPES.VETERAN]: CHARACTER_TYPES.RETIREE,
  [CHARACTER_TYPES.MOTHER]: CHARACTER_TYPES.VETERAN,
  [CHARACTER_TYPES.BUSINESSMAN]: CHARACTER_TYPES.MOTHER,
  [CHARACTER_TYPES.STUDENT]: CHARACTER_TYPES.BUSINESSMAN,
  [CHARACTER_TYPES.MOTOBOY]: CHARACTER_TYPES.STUDENT,
};

export const TELLER_TYPES = {
  ATM: 'ATM', // High capacity, low points
  HUMAN: 'HUMAN', // Normal capacity, normal points
  MANAGER: 'MANAGER', // Low capacity, double points
};
