export const ESPIAO_ENTRE_NOS_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  ASSIGNMENT: 'ASSIGNMENT',
  INVESTIGATION: 'INVESTIGATION',
  ASSESSMENT: 'ASSESSMENT',
  FINAL_ASSESSMENT: 'FINAL_ASSESSMENT',
  RESOLUTION: 'RESOLUTION',
  GAME_OVER: 'GAME_OVER',
};

export const ESPIAO_ENTRE_NOS_ACTIONS = {
  LAST_QUESTIONER: 'LAST_QUESTIONER',
  MAKE_ACCUSATION: 'MAKE_ACCUSATION',
  SUBMIT_VOTE: 'SUBMIT_VOTE',
  GUESS_LOCATION: 'GUESS_LOCATION',
};

export const PLAYER_COUNTS = {
  MIN: 4,
  MAX: 10,
};

export const LOCATIONS_USED_IN_A_ROUND = 25;

export const SPY = 'SPY';

export const GAME_DURATION = 10 * 60 * 1000; // 10 minutes

export const TIMER_STATUS = {
  RUNNING: 'RUNNING',
  STOPPED: 'STOPPED',
  PAUSED: 'PAUSED',
};

export const OUTCOMES = {
  VOTE_SUCCESS: 'VOTE_SUCCESS',
  VOTE_FAIL: 'VOTE_FAIL',
  CONTINUE: 'CONTINUE',
  SPY_GUESS: 'SPY_GUESS',
  VOTE_END: 'VOTE_END',
};

export const RESOLUTIONS = {
  SPY_GUESS: 'SPY_GUESS',
  SPY_FOUND: 'SPY_FOUND',
};
