export const METALINGUAGEM_PHASES = {
  WORD_CREATION: 'WORD_CREATION',
  GUESSING: 'GUESSING',
  RESULTS: 'RESULTS',
} as const;

export const METALINGUAGEM_ACTIONS = {
  SUBMIT_WORD: 'SUBMIT_WORD',
  SUBMIT_GUESS: 'SUBMIT_GUESS',
} as const;

export const WORD_LENGTH_STATUS = {
  AVAILABLE: 'AVAILABLE',
  ENDANGERED: 'ENDANGERED',
  SOLVED: 'SOLVED',
  FAILED: 'FAILED',
} as const;
