export const SONHOS_PESADELOS_PHASES = {
  DREAM_TELLING: 'DREAM_TELLING',
  MATCHING: 'MATCHING',
  RESOLUTION: 'RESOLUTION',
} as const;

export const SONHOS_PESADELOS_ACTIONS = {
  SUBMIT_DREAM: 'SUBMIT_DREAM',
  SUBMIT_VOTING: 'SUBMIT_VOTING',
} as const;
