export const ATTRIBUTES = [
  { id: 'alive', name: { en: 'Alive', pt: 'Vivo' } },
  { id: 'beautiful', name: { en: 'Beautiful', pt: 'Bonito' } },
  { id: 'big', name: { en: 'Big', pt: 'Grande' } },
  { id: 'bright', name: { en: 'Bright', pt: 'Brilho' } },
  { id: 'clothes', name: { en: 'Clothes', pt: 'Vestimenta' } },
  { id: 'danger', name: { en: 'Danger', pt: 'Perigo' } },
  { id: 'defense', name: { en: 'Defense', pt: 'Defesa' } },
  { id: 'fast', name: { en: 'Fast', pt: 'Rápido' } },
  { id: 'flight', name: { en: 'Flight', pt: 'Vôo' } },
  { id: 'food', name: { en: 'Food', pt: 'Comida' } },
  { id: 'heavy', name: { en: 'Heavy', pt: 'Pesado' } },
  { id: 'human', name: { en: 'Human', pt: 'Humano' } },
  { id: 'knowledge', name: { en: 'Knowledge', pt: 'Conhecimento' } },
  { id: 'liquid', name: { en: 'Liquid', pt: 'Líquido' } },
  { id: 'long', name: { en: 'Long', pt: 'Longo' } },
  { id: 'metal', name: { en: 'Metal', pt: 'Metal' } },
  { id: 'plant', name: { en: 'Plant', pt: 'Planta' } },
  { id: 'power', name: { en: 'Power', pt: 'Força' } },
  { id: 'round', name: { en: 'Round', pt: 'Redondo' } },
  { id: 'sharp', name: { en: 'Sharp', pt: 'Afiado' } },
  { id: 'solid', name: { en: 'Solid', pt: 'Sólido' } },
  { id: 'tool', name: { en: 'Tool', pt: 'Ferramenta' } },
  { id: 'valuable', name: { en: 'Valuable', pt: 'Valioso' } },
  { id: 'warm', name: { en: 'Warm', pt: 'Quente' } },
  { id: 'weapon', name: { en: 'Weapon', pt: 'Arma' } },
];

export const ATTRIBUTES_KEYS = [
  'alive',
  'beautiful',
  'big',
  'bright',
  'clothes',
  'danger',
  'defense',
  'fast',
  'flight',
  'food',
  'heavy',
  'human',
  'knowledge',
  'liquid',
  'long',
  'metal',
  'plant',
  'power',
  'round',
  'sharp',
  'solid',
  'tool',
  'valuable',
  'warm',
  'weapon',
] as const;
