export const UE_SO_ISSO_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  WORD_SELECTION: 'WORD_SELECTION',
  SUGGEST: 'SUGGEST',
  COMPARE: 'COMPARE',
  GUESS: 'GUESS',
  VERIFY_GUESS: 'VERIFY_GUESS',
  RESULT: 'RESULT',
  GAME_OVER: 'GAME_OVER',
};

export const UE_SO_ISSO_ACTIONS = {
  SUBMIT_VOTES: 'SUBMIT_VOTES',
  SUBMIT_SUGGESTIONS: 'SUBMIT_SUGGESTIONS',
  SUBMIT_OUTCOME: 'SUBMIT_OUTCOME',
  VALIDATE_SUGGESTION: 'VALIDATE_SUGGESTION',
  SEND_GUESS: 'SEND_GUESS',
  SUBMIT_VALIDATION: 'SUBMIT_VALIDATION',
};

export const UE_SO_ISSO_ACHIEVEMENTS = {
  MOST_ELIMINATED_CLUES: 'MOST_ELIMINATED_CLUES',
  FEWEST_ELIMINATED_CLUES: 'FEWEST_ELIMINATED_CLUES',
  LONGEST_CLUES: 'LONGEST_CLUES',
  SHORTEST_CLUES: 'SHORTEST_CLUES',
  MOST_PASSES: 'MOST_PASSES',
  BEST_GUESSER: 'BEST_GUESSER',
  WORST_GUESSER: 'WORST_GUESSER',
};

export const PLAYER_COUNTS = {
  MIN: 3,
  MAX: 10,
};

export const WORDS_PER_CARD = 5;

export const MAX_ROUNDS = 10;

export const OUTCOME = {
  CONTINUE: 'CONTINUE',
  WIN: 'WIN',
  LOSE: 'LOSE',
  WRONG: 'WRONG',
  CORRECT: 'CORRECT',
  INCONCLUSIVE: 'INCONCLUSIVE',
  PASS: 'PASS',
};

export const ALLOWED_MISTAKES = 3;
export const GOAL = 7;
export const CORRECT_GUESS_SCORE = 2;
export const INCORRECT_GUESS_SCORE = -1;
