export const UE_SO_ISSO_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  WORD_SELECTION: 'WORD_SELECTION',
  SUGGEST: 'SUGGEST',
  COMPARE: 'COMPARE',
  GUESS: 'GUESS',
  GAME_OVER: 'GAME_OVER',
};

export const UE_SO_ISSO_ACTIONS = {
  SUBMIT_VOTES: 'SUBMIT_VOTES',
  SUBMIT_SUGGESTIONS: 'SUBMIT_SUGGESTIONS',
  SUBMIT_OUTCOME: 'SUBMIT_OUTCOME',
  VALIDATE_SUGGESTION: 'VALIDATE_SUGGESTION',
  SEND_GUESS: 'SEND_GUESS',
  SUBMIT_VALIDATION: 'SUBMIT_VALIDATION',
};

export const PLAYER_COUNTS = {
  MIN: 3,
  MAX: 10,
};

export const WORDS_PER_CARD = 5;
