export const MEDIDAS_NAO_EXATAS_PHASES = {
  METRICS_BUILDING: 'METRICS_BUILDING',
  GUESSING: 'GUESSING',
  RESULTS: 'RESULTS',
} as const;

export const MEDIDAS_NAO_EXATAS_ACTIONS = {
  SUBMIT_POOL: 'SUBMIT_POOL',
  SUBMIT_METRICS: 'SUBMIT_METRICS',
  SUBMIT_GUESS: 'SUBMIT_GUESS',
} as const;

export const GUESSING_TIME = 120; // 2 minutes

export const METRIC_TIME = 10;
