export const ACTIONS = {
  SUBMIT_BAD_WORDS: 'SUBMIT_BAD_WORDS',
  SUBMIT_CLUES: 'SUBMIT_CLUES',
  SUBMIT_GUESS: 'SUBMIT_GUESS',
  UPDATE_CLOVER_STATE: 'UPDATE_CLOVER_STATE',
};

export const ROTATIONS = [0, 90, 180, 270];

export const WORST_TO_REMOVE = 6;
