export const MESMICE_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  CLUE_WRITING: 'CLUE_WRITING',
  OBJECT_FEATURE_ELIMINATION: 'OBJECT_FEATURE_ELIMINATION',
  RESULT: 'RESULT',
  GAME_OVER: 'GAME_OVER',
};
