export const FULFILLMENT_MOCK = {
  turnOrder: [
    '7bwydsYi6WVfc4oCdugENiBJrcq1',
    'OyQPdjqLovgTSn77Uh003YrxfpP2',
    'gxihf4jBPXY7TPZbqZcSgp64lpF2',
    'YKj56X0vMAUYUgVn9AEZOS0zAJU2',
  ],
  previousBossIdea: null,
  currentGoodId: 'good-61',
  status: {
    outcome: 'CONTINUE',
    progress: 5,
    goal: 6,
    stocked: 32,
    total: 33,
  },
  phase: 'FULFILLMENT',
  reportedOutOfStockGoodIds: [],
  warehouseGrid: {
    0: {
      id: 0,
      goodId: 'good-212',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    1: {
      id: 1,
      goodId: 'good-157',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    2: {
      id: 2,
      goodId: 'good-160',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    3: {
      id: 3,
      goodId: 'good-48',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    4: {
      id: 4,
      goodId: 'good-252',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    5: {
      id: 5,
      goodId: 'good-188',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    6: {
      id: 6,
      goodId: 'good-22',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    7: {
      id: 7,
      goodId: 'good-2',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    8: {
      id: 8,
      goodId: 'good-21',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    9: {
      id: 9,
      goodId: 'good-109',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    10: {
      id: 10,
      goodId: 'good-222',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    11: {
      id: 11,
      goodId: 'good-19',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    12: {
      id: 12,
      goodId: 'good-149',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    13: {
      id: 13,
      goodId: 'good-41',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    14: {
      id: 14,
      goodId: 'good-196',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    15: {
      id: 15,
      goodId: 'good-227',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    16: {
      id: 16,
      goodId: 'good-189',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    17: {
      id: 17,
      goodId: 'good-60',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    18: {
      id: 18,
      goodId: 'good-99',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    19: {
      id: 19,
      goodId: 'good-57',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    20: {
      id: 20,
      goodId: 'good-77',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    21: {
      id: 21,
      goodId: null,
      available: false,
      temporaryName: 'A',
      orderId: null,
      status: 'idle',
    },
    22: {
      id: 22,
      goodId: null,
      available: false,
      temporaryName: 'B',
      orderId: null,
      status: 'idle',
    },
    23: {
      id: 23,
      goodId: 'good-76',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    24: {
      id: 24,
      goodId: 'good-247',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    25: {
      id: 25,
      goodId: 'good-186',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    26: {
      id: 26,
      goodId: 'good-61',
      available: false,
      temporaryName: 'C',
      orderId: null,
      status: 'idle',
    },
    27: {
      id: 27,
      goodId: 'good-36',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    28: {
      id: 28,
      goodId: null,
      available: false,
      temporaryName: 'D',
      orderId: null,
      status: 'idle',
    },
    29: {
      id: 29,
      goodId: 'good-127',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    30: {
      id: 30,
      goodId: null,
      available: false,
      temporaryName: 'E',
      orderId: null,
      status: 'idle',
    },
    31: {
      id: 31,
      goodId: null,
      available: false,
      temporaryName: 'F',
      orderId: null,
      status: 'idle',
    },
    32: {
      id: 32,
      goodId: null,
      available: false,
      temporaryName: 'G',
      orderId: null,
      status: 'idle',
    },
    33: {
      id: 33,
      goodId: null,
      available: false,
      temporaryName: 'H',
      orderId: null,
      status: 'idle',
    },
    34: {
      id: 34,
      goodId: null,
      available: false,
      temporaryName: 'I',
      orderId: null,
      status: 'idle',
    },
    35: {
      id: 35,
      goodId: 'good-110',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    36: {
      id: 36,
      goodId: 'good-213',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    37: {
      id: 37,
      goodId: null,
      available: false,
      temporaryName: 'J',
      orderId: null,
      status: 'idle',
    },
    38: {
      id: 38,
      goodId: null,
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    39: {
      id: 39,
      goodId: null,
      available: false,
      temporaryName: 'K',
      orderId: null,
      status: 'idle',
    },
    40: {
      id: 40,
      goodId: 'good-152',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    41: {
      id: 41,
      goodId: null,
      available: false,
      temporaryName: 'L',
      orderId: null,
      status: 'idle',
    },
    42: {
      id: 42,
      goodId: 'good-245',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    43: {
      id: 43,
      goodId: 'good-151',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    44: {
      id: 44,
      goodId: 'good-43',
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    45: {
      id: 45,
      goodId: null,
      available: false,
      temporaryName: 'M',
      orderId: null,
      status: 'idle',
    },
    46: {
      id: 46,
      goodId: null,
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
    47: {
      id: 47,
      goodId: null,
      available: false,
      temporaryName: 'N',
      orderId: null,
      status: 'idle',
    },
    48: {
      id: 48,
      goodId: null,
      available: false,
      temporaryName: null,
      orderId: null,
      status: 'idle',
    },
  },
  ordersLeft: 33,
  goodsDict: {
    'good-247': {
      id: 'good-247',
      slot: 24,
      exposed: false,
      orientation: 0,
    },
    'good-21': {
      id: 'good-21',
      slot: 8,
      exposed: false,
      orientation: 180,
    },
    'good-149': {
      id: 'good-149',
      slot: 12,
      exposed: false,
      orientation: 0,
    },
    'good-213': {
      id: 'good-213',
      slot: 36,
      exposed: false,
      orientation: 90,
    },
    'good-152': {
      id: 'good-152',
      slot: 40,
      exposed: false,
      orientation: 270,
    },
    'good-61': {
      id: 'good-61',
      slot: 26,
      exposed: false,
      orientation: 0,
    },
    'good-127': {
      id: 'good-127',
      slot: 29,
      exposed: false,
      orientation: 0,
    },
    'good-245': {
      id: 'good-245',
      slot: 42,
      exposed: false,
      orientation: 270,
    },
    'good-43': {
      id: 'good-43',
      slot: 44,
      exposed: false,
      orientation: 0,
    },
    'good-36': {
      id: 'good-36',
      slot: 27,
      exposed: false,
      orientation: 270,
    },
    'good-2': {
      id: 'good-2',
      slot: 7,
      exposed: false,
      orientation: 90,
    },
    'good-186': {
      id: 'good-186',
      slot: 25,
      exposed: false,
      orientation: 0,
    },
    'good-196': {
      id: 'good-196',
      slot: 14,
      exposed: false,
      orientation: 0,
    },
    'good-212': {
      id: 'good-212',
      slot: 0,
      exposed: false,
      orientation: 90,
    },
    'good-227': {
      id: 'good-227',
      slot: 15,
      exposed: false,
      orientation: 0,
    },
    'good-76': {
      id: 'good-76',
      slot: 23,
      exposed: false,
      orientation: 0,
    },
    'good-189': {
      id: 'good-189',
      slot: 16,
      exposed: false,
      orientation: 0,
    },
    'good-109': {
      id: 'good-109',
      slot: 9,
      exposed: false,
      orientation: 0,
    },
    'good-151': {
      id: 'good-151',
      slot: 43,
      exposed: false,
      orientation: 180,
    },
    'good-110': {
      id: 'good-110',
      slot: 35,
      exposed: false,
      orientation: 90,
    },
    'good-57': {
      id: 'good-57',
      slot: 19,
      exposed: false,
      orientation: 0,
    },
    'good-222': {
      id: 'good-222',
      slot: 10,
      exposed: false,
      orientation: 0,
    },
    'good-77': {
      id: 'good-77',
      slot: 20,
      exposed: false,
      orientation: 180,
    },
    'good-157': {
      id: 'good-157',
      slot: 1,
      exposed: false,
      orientation: 0,
    },
    'good-160': {
      id: 'good-160',
      slot: 2,
      exposed: false,
      orientation: 180,
    },
    'good-252': {
      id: 'good-252',
      slot: 4,
      exposed: false,
      orientation: 0,
    },
    'good-22': {
      id: 'good-22',
      slot: 6,
      exposed: false,
      orientation: 180,
    },
    'good-48': {
      id: 'good-48',
      slot: 3,
      exposed: false,
      orientation: 90,
    },
    'good-188': {
      id: 'good-188',
      slot: 5,
      exposed: false,
      orientation: 0,
    },
    'good-99': {
      id: 'good-99',
      slot: 18,
      exposed: false,
      orientation: 0,
    },
    'good-19': {
      id: 'good-19',
      slot: 11,
      exposed: false,
      orientation: 90,
    },
    'good-41': {
      id: 'good-41',
      slot: 13,
      exposed: false,
      orientation: 270,
    },
    'good-60': {
      id: 'good-60',
      slot: 17,
      exposed: false,
      orientation: 270,
    },
    'good-166': {
      id: 'good-166',
      slot: null,
      exposed: false,
      orientation: 180,
    },
    'good-84': {
      id: 'good-84',
      slot: null,
      exposed: false,
      orientation: 0,
    },
    'good-240': {
      id: 'good-240',
      slot: null,
      exposed: false,
      orientation: 270,
    },
    'good-153': {
      id: 'good-153',
      slot: null,
      exposed: false,
      orientation: 0,
    },
    'good-67': {
      id: 'good-67',
      slot: null,
      exposed: false,
      orientation: 0,
    },
    'good-216': {
      id: 'good-216',
      slot: null,
      exposed: false,
      orientation: 180,
    },
    'good-195': {
      id: 'good-195',
      slot: null,
      exposed: false,
      orientation: 0,
    },
    'good-250': {
      id: 'good-250',
      slot: null,
      exposed: false,
      orientation: 180,
    },
    'good-16': {
      id: 'good-16',
      slot: null,
      exposed: false,
      orientation: 0,
    },
    'good-122': {
      id: 'good-122',
      slot: null,
      exposed: false,
      orientation: 0,
    },
    'good-255': {
      id: 'good-255',
      slot: null,
      exposed: false,
      orientation: 0,
    },
    'good-254': {
      id: 'good-254',
      slot: null,
      exposed: false,
      orientation: 180,
    },
  },
  round: {
    current: 1,
    total: 3,
  },
  lastBossIdea: {
    id: 'FOCUS',
    type: 'communication',
    title: {
      en: 'Provisional measure: Silence',
      pt: 'Medida provisória: Silêncio',
    },
    subtitle: {
      pt: 'Conversa fiada faz mal ao trabalho!',
      en: 'Chit-chat is bad for work!',
    },
    description: {
      en: 'Each worker can only say the letter where they want the good to be placed',
      pt: 'Cada trabalhador só pode dizer a letra onde deseja que a mercadoria seja colocada, nada mais!',
    },
    afterPlacement: {
      en: 'Storing the packed goods keeps them protected! Talk freely now',
      pt: 'Embalar os produtos os deixam protegidos! Conversem livremente agora',
    },
    ogRule: 'Could have been an email',
    difficulty: 3,
  },
  event: {
    actorId: 'YKj56X0vMAUYUgVn9AEZOS0zAJU2',
    goodsIds: ['good-61'],
    type: 'CONCEAL',
  },
  updatedAt: 1781459280537,
  players: {
    YKj56X0vMAUYUgVn9AEZOS0zAJU2: {
      id: 'YKj56X0vMAUYUgVn9AEZOS0zAJU2',
      name: 'KavDev',
      avatarId: '0',
      type: 'player',
      ready: false,
      score: 0,
      updatedAt: 1781457931402,
      isGuest: false,
      orders: [
        'good-213',
        'good-57',
        'good-227',
        'good-195',
        'good-127',
        'good-84',
        'good-99',
        'good-166',
        'good-255',
        'good-110',
        'good-160',
      ],
      previousOrders: [],
      fulfillments: {},
    },
    OyQPdjqLovgTSn77Uh003YrxfpP2: {
      id: 'OyQPdjqLovgTSn77Uh003YrxfpP2',
      name: 'Oliver',
      avatarId: '32',
      type: 'player',
      score: 0,
      updatedAt: 1781457919674,
      isGuest: false,
      ready: false,
      orders: [
        'good-48',
        'good-22',
        'good-245',
        'good-67',
        'good-16',
        'good-77',
        'good-149',
        'good-19',
        'good-212',
        'good-76',
        'good-254',
      ],
      previousOrders: [],
      fulfillments: {},
    },
    gxihf4jBPXY7TPZbqZcSgp64lpF2: {
      id: 'gxihf4jBPXY7TPZbqZcSgp64lpF2',
      name: 'Max',
      avatarId: '12',
      type: 'player',
      score: 0,
      updatedAt: 1781457925999,
      isGuest: false,
      orders: [
        'good-189',
        'good-109',
        'good-186',
        'good-247',
        'good-240',
        'good-151',
        'good-60',
        'good-41',
        'good-2',
        'good-36',
        'good-250',
      ],
      previousOrders: [],
      fulfillments: {},
      ready: false,
    },
    '7bwydsYi6WVfc4oCdugENiBJrcq1': {
      id: '7bwydsYi6WVfc4oCdugENiBJrcq1',
      name: 'Eva',
      avatarId: '20',
      type: 'player',
      score: 0,
      updatedAt: 1781457914630,
      isGuest: false,
      orders: [
        'good-157',
        'good-252',
        'good-188',
        'good-196',
        'good-222',
        'good-43',
        'good-152',
        'good-122',
        'good-61',
        'good-153',
        'good-21',
      ],
      previousOrders: [],
      fulfillments: {},
      ready: false,
    },
  },
};
