export const PLANEJAMENTO_URBANO_PHASES = {
  LOBBY: 'LOBBY',
  SETUP: 'SETUP',
  PLANNING: 'PLANNING',
  PLACING: 'PLACING',
  RESOLUTION: 'RESOLUTION',
  GAME_OVER: 'GAME_OVER',
};

export const PLANEJAMENTO_URBANO_ACTIONS = {
  SUBMIT_PLANNING: 'SUBMIT_PLANNING',
  SUBMIT_PLACEMENTS: 'SUBMIT_PLACEMENTS',
};

export const PLANEJAMENTO_URBANO_ACHIEVEMENTS = {};

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 8,
};

export const TOTAL_ROUNDS = 6;
export const LOCATIONS_PER_ROUND = 3;
export const CITY_BOUNDS_SIZE = 7;

export const ARCHITECT_MATCH_POINTS = 3;
export const PLAYER_MATCH_POINTS = 1;
