export const PLANEJAMENTO_URBANO_PHASES = {
  LOBBY: 'LOBBY',
  SETUP: 'SETUP',
  PLANNING: 'PLANNING',
  PLACING: 'PLACING',
  RESOLUTION: 'RESOLUTION',
  GAME_OVER: 'GAME_OVER',
};

export const PLANEJAMENTO_URBANO_ACTIONS = {
  SUBMIT_PLANNING: 'SUBMIT_PLANNING',
  SUBMIT_PLACEMENTS: 'SUBMIT_PLACEMENTS',
};

export const PLANEJAMENTO_URBANO_ACHIEVEMENTS = {
  MOST_CONE_A_LEFT: 'MOST_CONE_A_LEFT',
  MOST_CONE_B_LEFT: 'MOST_CONE_B_LEFT',
  MOST_CONE_C_LEFT: 'MOST_CONE_C_LEFT',
  MOST_CONE_D_LEFT: 'MOST_CONE_D_LEFT',
  MOST_ARCHITECT_MATCHES: 'MOST_ARCHITECT_MATCHES',
  MOST_OTHER_PLAYERS_MATCHES: 'MOST_OTHER_PLAYERS_MATCHES',
  MOST_SOLO_GUESSES: 'MOST_SOLO_GUESSES',
};

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 8,
};

export const TOTAL_ROUNDS = 6;
export const LOCATIONS_PER_ROUND = 3;
export const CITY_BOUNDS_SIZE = 7;

export const ARCHITECT_MATCH_POINTS = 3;
export const PLAYER_MATCH_POINTS = 1;

export const CONES = ['A', 'B', 'C', 'D'] as const;
