export const TA_NA_CARA_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  PROMPT: 'PROMPT',
  ANSWERING: 'ANSWERING',
  GUESSING: 'GUESSING',
  REVEAL: 'REVEAL',
  GAME_OVER: 'GAME_OVER',
};

export const TA_NA_CARA_ACTIONS = {
  SUBMIT_PROMPT: 'SUBMIT_PROMPT',
  SUBMIT_TARGET: 'SUBMIT_TARGET',
  SUBMIT_GUESS: 'SUBMIT_GUESS',
  SUBMIT_ANSWER: 'SUBMIT_ANSWER',
};

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 10,
};

export const MAX_ROUNDS = 15;

export const MINIMUM_SUSPECTS = 12;

export const QUESTIONS_PER_PLAYER = 6;
