export const TA_NA_CARA_PHASES = {
  LOBBY: 'LOBBY',
  SETUP: 'SETUP',
  IDENTITY_SELECTION: 'IDENTITY_SELECTION',
  PROMPTING: 'PROMPTING',
  ANSWERING: 'ANSWERING',
  GUESSING: 'GUESSING',
  REVEAL: 'REVEAL',
  GAME_OVER: 'GAME_OVER',
};

export const TA_NA_CARA_ACTIONS = {
  SUBMIT_IDENTITY: 'SUBMIT_IDENTITY',
  SUBMIT_PROMPT: 'SUBMIT_PROMPT',
  SUBMIT_ANSWER: 'SUBMIT_ANSWER',
  SUBMIT_GUESSES: 'SUBMIT_GUESSES',
};

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 9,
};

export const MAX_ROUNDS = 3;

export const MIN_QUESTIONS_PER_ROUND = 5;

export const GRID_SIZE = 18;

export const CORRECT_POINTS = 5;
export const GUESSED_POINTS = 2;

export const CUSTOM_QUESTION_ID = 'CUSTOM';
