export const TA_NA_CARA_PHASES = {
  SETUP: 'SETUP',
  PROMPT: 'PROMPT',
  ANSWERING: 'ANSWERING',
  GUESSING: 'GUESSING',
  GAME_OVER: 'GAME_OVER',
} as const;

export const TA_NA_CARA_ACTIONS = {
  SUBMIT_PROMPT: 'SUBMIT_PROMPT',
  SUBMIT_ANSWER: 'SUBMIT_ANSWER',
  SUBMIT_GUESS: 'SUBMIT_GUESS',
  TRIGGER_GUESSING: 'TRIGGER_GUESSING',
} as const;

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 2,
} as const;

export const MAX_ROUNDS = 14;

export const CHARACTER_COUNT = 24;
