export const VAMOS_AO_CINEMA_PHASES = {
  MOVIE_SELECTION: 'MOVIE_SELECTION',
  MOVIE_ELIMINATION: 'MOVIE_ELIMINATION',
  REVEAL: 'REVEAL',
} as const;

export const VAMOS_AO_CINEMA_ACTIONS = {
  SELECT_MOVIE: 'SELECT_MOVIE',
  ELIMINATE_MOVIE: 'ELIMINATE_MOVIE',
  VOTE_FOR_POSTER: 'VOTE_FOR_POSTER',
} as const;
