export const LINHAS_CRUZADAS_ACTIONS = {
  SUBMIT_PROMPT: 'SUBMIT_PROMPT',
  SUBMIT_DRAWING: 'SUBMIT_DRAWING',
  SUBMIT_GUESS: 'SUBMIT_GUESS',
} as const;

export const DRAWING_TIME_IN_SECONDS = 120;

export const SLIDE_DURATION = 7;
