// Types
import type { AchievementReference } from 'types/achievements';

export const ACHIEVEMENTS = {
  MOST_LODGES: 'MOST_LODGES',
  MOST_GROUP_BETS: 'MOST_GROUP_BETS',
  FEWEST_GROUP_BETS: 'FEWEST_GROUP_BETS',
  MOST_GROUP_INITIAL_BETS: 'MOST_GROUP_INITIAL_BETS',
  FEWEST_GROUP_INITIAL_BETS: 'FEWEST_GROUP_INITIAL_BETS',
  MOST_GROUP_BOOST_BETS: 'MOST_GROUP_BOOST_BETS',
  FEWEST_GROUP_BOOST_BETS: 'FEWEST_GROUP_BOOST_BETS',
  MOST_GROUP_FINAL_BETS: 'MOST_GROUP_FINAL_BETS',
  FEWEST_GROUP_FINAL_BETS: 'FEWEST_GROUP_FINAL_BETS',
  ONLY_LODGE: 'ONLY_LODGE',
  MOST_PLAYER_BETS: 'MOST_PLAYER_BETS',
  FEWEST_PLAYER_BETS: 'FEWEST_PLAYER_BETS',
};

export const achievementsReference: AchievementReference = {};

export default achievementsReference;
