export const COMUNICACAO_ALIENIGENA_PHASES = {
  ALIEN_SELECTION: 'ALIEN_SELECTION',
  ALIEN_SEEDING: 'ALIEN_SEEDING',
  HUMANS_ASKS: 'HUMANS_ASKS',
  ALIEN_ANSWER: 'ALIEN_ANSWER',
  ALIEN_REQUEST: 'ALIEN_REQUEST',
  OFFERINGS: 'OFFERINGS',
  REVEAL: 'REVEAL',
} as const;

export const COMUNICACAO_ALIENIGENA_ACTIONS = {
  SUBMIT_ALIEN: 'SUBMIT_ALIEN',
  SUBMIT_SEEDS: 'SUBMIT_SEEDS',
  SUBMIT_HUMAN_INQUIRY: 'SUBMIT_HUMAN_INQUIRY',
  SUBMIT_ALIEN_RESPONSES: 'SUBMIT_ALIEN_RESPONSES',
  CONFIRM_NOTES: 'CONFIRM_NOTES',
  SUBMIT_ALIEN_REQUEST: 'SUBMIT_ALIEN_REQUEST',
  SUBMIT_OFFERINGS: 'SUBMIT_OFFERINGS',
} as const;

export const ALIEN_CANVAS = {
  WIDTH: 500,
  HEIGHT: 120,
};

export const ITEM_TYPES = {
  ITEM: 'ITEM',
  CURSE: 'CURSE',
  BLANK: 'BLANK',
} as const;

export const BADGE_INSTRUCTION = {
  pt: 'Quantas vezes esse item foi parte de uma pergunta',
  en: 'How many times this item was part of a question',
};

export const SPRITE_SIZE = 48;

export const MAX_INQUIRY_OBJECTS = 5;
