export const SUPER_CAMPEONATO_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  CHALLENGE_SELECTION: 'CHALLENGE_SELECTION',
  CONTENDER_SELECTION: 'CONTENDER_SELECTION',
  BETS: 'BETS',
  BATTLE: 'BATTLE',
  RESULTS: 'RESULTS',
  GAME_OVER: 'GAME_OVER',
};

export const PLAYER_COUNTS = {
  MIN: 3,
  MAX: 8,
};

export const TOTAL_ROUNDS = 5;

export const CONTENDERS_PER_ROUND = 8;

export const CONTENDERS_PER_PLAYER = 5;

export const CHALLENGES_PER_ROUND = 2;

export const CHALLENGES_PER_GAME = CHALLENGES_PER_ROUND * TOTAL_ROUNDS;
