export const SUPER_CAMPEONATO_PHASES = {
  LOBBY: 'LOBBY',
  SETUP: 'SETUP',
  CHALLENGE_SELECTION: 'CHALLENGE_SELECTION',
  CONTENDER_SELECTION: 'CONTENDER_SELECTION',
  BETS: 'BETS',
  BATTLE: 'BATTLE',
  RESULTS: 'RESULTS',
  GAME_OVER: 'GAME_OVER',
};

export const SUPER_CAMPEONATO_ACTIONS = {
  SUBMIT_CHALLENGE: 'SUBMIT_CHALLENGE',
  SUBMIT_CONTENDERS: 'SUBMIT_CONTENDERS',
  SUBMIT_BETS: 'SUBMIT_BETS',
  SUBMIT_VOTES: 'SUBMIT_VOTES',
};

export const PLAYER_COUNTS = {
  MIN: 3,
  MAX: 30,
};

export const SUPER_CAMPEONATO_ACHIEVEMENTS = {
  BEST_QUARTER_BETS: 'BEST_QUARTER_BETS',
  BEST_SEMI_BETS: 'BEST_SEMI_BETS',
  BEST_FINAL_BETS: 'BEST_FINAL_BETS',
  BEST_OVERALL_BETS: 'BEST_OVERALL_BETS',
  WORST_QUARTER_BETS: 'WORST_QUARTER_BETS',
  WORST_SEMI_BETS: 'WORST_SEMI_BETS',
  WORST_FINAL_BETS: 'WORST_FINAL_BETS',
  WORST_OVERALL_BETS: 'WORST_OVERALL_BETS',
  BEST_QUARTER_CONTENDERS: 'BEST_QUARTER_CONTENDERS',
  BEST_SEMI_CONTENDERS: 'BEST_SEMI_CONTENDERS',
  BEST_FINAL_CONTENDERS: 'BEST_FINAL_CONTENDERS',
  WORST_QUARTER_CONTENDERS: 'WORST_QUARTER_CONTENDERS',
  WORST_SEMI_CONTENDERS: 'WORST_SEMI_CONTENDERS',
  WORST_FINAL_CONTENDERS: 'WORST_FINAL_CONTENDERS',
  BEST_CONTENDERS: 'BEST_CONTENDERS',
  WORST_CONTENDER: 'WORST_CONTENDER',
  MOST_GROUP_VOTES: 'MOST_GROUP_VOTES',
  SOLITAIRE_VOTE: 'SOLITAIRE_VOTE',
};

export const TOTAL_ROUNDS = 5;

export const CONTENDERS_PER_ROUND = 8;

export const CONTENDERS_PER_PLAYER = 8;

export const CHALLENGES_PER_ROUND = 2;

export const CHALLENGES_PER_GAME = CHALLENGES_PER_ROUND * TOTAL_ROUNDS;

export const CHAMPIONSHIP_ORDER = ['quarter', 'semi', 'final'];
