export const PORTA_DOS_DESESPERADOS_PHASES = {
  BOOK_POSSESSION: 'BOOK_POSSESSION',
  DOOR_CHOICE: 'DOOR_CHOICE',
  RESOLUTION: 'RESOLUTION',
} as const;

export const PORTA_DOS_DESESPERADOS_ACTIONS = {
  SUBMIT_PAGES: 'SUBMIT_PAGES',
  SUBMIT_DOOR: 'SUBMIT_DOOR',
} as const;

export const TOTAL_DOORS = 7;

export const TRAPS = {
  MORE_CLUES: 'MORE_CLUES',
  FEWER_PAGES: 'FEWER_PAGES',
  SEPIA: 'SEPIA',
  NO_PREVIEW: 'NO_PREVIEW',
  CONCEALED_DOOR: 'CONCEALED_DOOR',
  EXTRA_DOOR: 'EXTRA_DOOR',
  DOUBLE_MAGIC: 'DOUBLE_MAGIC',
  ORDERED_DOORS: 'ORDERED_DOORS',
  SECRET_CHOICE: 'SECRET_CHOICE',
  RANDOM_INTERJECTION: 'RANDOM_INTERJECTION',
  HALF_TIME: 'HALF_TIME',
  DANCING_DOORS: 'DANCING_DOORS',
  FADED_DOORS: 'FADED_DOORS',
  BLIND_DOOR: 'BLIND_DOOR',
  VANISHING_DOORS: 'VANISHING_DOORS',
  LOCKED_CHOICE: 'LOCKED_CHOICE',
  SHUFFLED_DOORS: 'SHUFFLED_DOORS',
  FLIP_BOOK: 'FLIP_BOOK',
};

export const OUTCOME = {
  SUCCESS: 'SUCCESS',
  FAIL: 'FAIL',
  LOSE: 'LOSE',
  WIN: 'WIN',
};

/**
 * In minutes
 */
export const ROUND_DURATION = 3;

/**
 * In seconds
 */
export const TIMER_LEAD = 10;
