export const ONDA_TELEPATICA_PHASES = {
  DIAL_CLUE: 'DIAL_CLUE',
  GUESS: 'GUESS',
  REVEAL: 'REVEAL',
} as const;

export const ONDA_TELEPATICA_ACTIONS = {
  SUBMIT_CATEGORY: 'SUBMIT_CATEGORY',
  SUBMIT_CLUE: 'SUBMIT_CLUE',
  SUBMIT_GUESS: 'SUBMIT_GUESS',
} as const;
