// Types
import type { GameInfo } from 'types/game-info';

/**
 * Lazy loads all game info JSON files
 * Using dynamic imports to prevent loading all game-info.json files on the home page
 */
export const getGameList = async (): Promise<Record<string, GameInfo>> => {
  const [
    ADEDANHX,
    ARTE_RUIM,
    BARRADOS_NA_ALFANDEGA,
    BOMBA_RELOGIO,
    CINEGRAFISTAS_AMADORES,
    COLEGAS_DE_QUARTO,
    COMUNICACAO_ALIENIGENA,
    COMUNICACAO_DUO,
    CONTADORES_HISTORIAS,
    CONTROLE_DE_ESTOQUE,
    CRIMES_HEDIONDOS,
    CRUZA_PALAVRAS,
    DETETIVES_IMAGINATIVOS,
    DUETOS,
    ESCAPE_ROOM,
    ESPIAO_ENTRE_NOS,
    ESQUIADORES,
    FILEIRA_DE_FATOS,
    FOFOCA_QUENTE,
    GALERIA_DE_SONHOS,
    IDADE_DA_PREDA,
    INSTRUMENTOS_CODIFICADOS,
    LABIRINTO_SECRETO,
    LINHAS_CRUZADAS,
    MEDIDAS_NAO_EXATAS,
    MEGAMIX,
    MEGAROBOS,
    MENTE_COLETIVA,
    MESMICE,
    METALINGUAGEM,
    NA_RUA_DO_MEDO,
    NAMORO_OU_AMIZADE,
    NAO_SOU_ROBO,
    NAUFRAGOS,
    ONDA_TELEPATICA,
    PALHETA_DE_CORES,
    PIQUE_PEGA,
    PLANEJAMENTO_URBANO,
    POLEMICA_DA_VEZ,
    PORTA_DOS_DESESPERADOS,
    QUAL_QUESITO,
    QUEM_NAO_MATA,
    QUEM_SOU_EU,
    RETRATO_FALADO,
    SENSO_LITERARIO,
    SINAIS_DE_ALERTA,
    SONHINHO_BOM,
    SONHOS_PESADELOS,
    SUPER_CAMPEONATO,
    TA_NA_CARA,
    TEORIA_DE_CONJUNTOS,
    TESTE_DE_ELENCO,
    TESTEMUNHA_OCULAR,
    TREVO_DA_SORTE,
    UE_SO_ISSO,
    VAMOS_AO_CINEMA,
    VENDAVAL_DE_PALPITE,
    VICE_CAMPEAO,
    VINGATIVOS,
  ] = await Promise.all([
    import('games/adedanhx/game-info.json'),
    import('games/arte-ruim/game-info.json'),
    import('games/barrados-na-alfandega/game-info.json'),
    import('games/bomba-relogio/game-info.json'),
    import('games/cinegrafistas-amadores/game-info.json'),
    import('games/colegas-de-quarto/game-info.json'),
    import('games/comunicacao-alienigena/game-info.json'),
    import('games/comunicacao-duo/game-info.json'),
    import('games/contadores-historias/game-info.json'),
    import('games/controle-de-estoque/game-info.json'),
    import('games/crimes-hediondos/game-info.json'),
    import('games/cruza-palavras/game-info.json'),
    import('games/detetives-imaginativos/game-info.json'),
    import('games/duetos/game-info.json'),
    import('games/escape-room/game-info.json'),
    import('games/espiao-entre-nos/game-info.json'),
    import('games/esquiadores/game-info.json'),
    import('games/fileira-de-fatos/game-info.json'),
    import('games/fofoca-quente/game-info.json'),
    import('games/galeria-de-sonhos/game-info.json'),
    import('games/idade-da-preda/game-info.json'),
    import('games/instrumentos-codificados/game-info.json'),
    import('games/labirinto-secreto/game-info.json'),
    import('games/linhas-cruzadas/game-info.json'),
    import('games/medidas-nao-exatas/game-info.json'),
    import('games/megamix/game-info.json'),
    import('games/megarobos/game-info.json'),
    import('games/mente-coletiva/game-info.json'),
    import('games/mesmice/game-info.json'),
    import('games/metalinguagem/game-info.json'),
    import('games/na-rua-do-medo/game-info.json'),
    import('games/namoro-ou-amizade/game-info.json'),
    import('games/nao-sou-robo/game-info.json'),
    import('games/naufragos/game-info.json'),
    import('games/onda-telepatica/game-info.json'),
    import('games/palheta-de-cores/game-info.json'),
    import('games/pique-pega/game-info.json'),
    import('games/planejamento-urbano/game-info.json'),
    import('games/polemica-da-vez/game-info.json'),
    import('games/porta-dos-desesperados/game-info.json'),
    import('games/qual-quesito/game-info.json'),
    import('games/quem-nao-mata/game-info.json'),
    import('games/quem-sou-eu/game-info.json'),
    import('games/retrato-falado/game-info.json'),
    import('games/senso-literario/game-info.json'),
    import('games/sinais-de-alerta/game-info.json'),
    import('games/sonhinho-bom/game-info.json'),
    import('games/sonhos-pesadelos/game-info.json'),
    import('games/super-campeonato/game-info.json'),
    import('games/ta-na-cara/game-info.json'),
    import('games/teoria-de-conjuntos/game-info.json'),
    import('games/teste-de-elenco/game-info.json'),
    import('games/testemunha-ocular/game-info.json'),
    import('games/trevo-da-sorte/game-info.json'),
    import('games/ue-so-isso/game-info.json'),
    import('games/vamos-ao-cinema/game-info.json'),
    import('games/vendaval-de-palpite/game-info.json'),
    import('games/vice-campeao/game-info.json'),
    import('games/vingativos/game-info.json'),
  ]);

  return {
    adedanhx: ADEDANHX.default,
    'arte-ruim': ARTE_RUIM.default,
    'barrados-na-alfandega': BARRADOS_NA_ALFANDEGA.default,
    'bomba-relogio': BOMBA_RELOGIO.default,
    'cinegrafistas-amadores': CINEGRAFISTAS_AMADORES.default,
    'colegas-de-quarto': COLEGAS_DE_QUARTO.default,
    'comunicacao-alienigena': COMUNICACAO_ALIENIGENA.default,
    'comunicacao-duo': COMUNICACAO_DUO.default,
    'contadores-historias': CONTADORES_HISTORIAS.default,
    'controle-de-estoque': CONTROLE_DE_ESTOQUE.default,
    'crimes-hediondos': CRIMES_HEDIONDOS.default,
    'cruza-palavras': CRUZA_PALAVRAS.default,
    'detetives-imaginativos': DETETIVES_IMAGINATIVOS.default,
    esquiadores: ESQUIADORES.default,
    duetos: DUETOS.default,
    'escape-room': ESCAPE_ROOM.default,
    'espiao-entre-nos': ESPIAO_ENTRE_NOS.default,
    'fileira-de-fatos': FILEIRA_DE_FATOS.default,
    'fofoca-quente': FOFOCA_QUENTE.default,
    'galeria-de-sonhos': GALERIA_DE_SONHOS.default,
    'idade-da-preda': IDADE_DA_PREDA.default,
    'instrumentos-codificados': INSTRUMENTOS_CODIFICADOS.default,
    'labirinto-secreto': LABIRINTO_SECRETO.default,
    'linhas-cruzadas': LINHAS_CRUZADAS.default,
    'medidas-nao-exatas': MEDIDAS_NAO_EXATAS.default,
    megamix: MEGAMIX.default,
    megarobos: MEGAROBOS.default,
    'mente-coletiva': MENTE_COLETIVA.default,
    mesmice: MESMICE.default,
    metalinguagem: METALINGUAGEM.default,
    'na-rua-do-medo': NA_RUA_DO_MEDO.default,
    'namoro-ou-amizade': NAMORO_OU_AMIZADE.default,
    'nao-sou-robo': NAO_SOU_ROBO.default,
    naufragos: NAUFRAGOS.default,
    'onda-telepatica': ONDA_TELEPATICA.default,
    'palheta-de-cores': PALHETA_DE_CORES.default,
    'planejamento-urbano': PLANEJAMENTO_URBANO.default,
    'pique-pega': PIQUE_PEGA.default,
    'polemica-da-vez': POLEMICA_DA_VEZ.default,
    'porta-dos-desesperados': PORTA_DOS_DESESPERADOS.default,
    'qual-quesito': QUAL_QUESITO.default,
    'quem-nao-mata': QUEM_NAO_MATA.default,
    'quem-sou-eu': QUEM_SOU_EU.default,
    'retrato-falado': RETRATO_FALADO.default,
    'senso-literario': SENSO_LITERARIO.default,
    'sinais-de-alerta': SINAIS_DE_ALERTA.default,
    'sonhinho-bom': SONHINHO_BOM.default,
    'sonhos-pesadelos': SONHOS_PESADELOS.default,
    'super-campeonato': SUPER_CAMPEONATO.default,
    'ta-na-cara': TA_NA_CARA.default,
    'teoria-de-conjuntos': TEORIA_DE_CONJUNTOS.default,
    'testemunha-ocular': TESTEMUNHA_OCULAR.default,
    'teste-de-elenco': TESTE_DE_ELENCO.default,
    'trevo-da-sorte': TREVO_DA_SORTE.default,
    'ue-so-isso': UE_SO_ISSO.default,
    'vamos-ao-cinema': VAMOS_AO_CINEMA.default,
    'vendaval-de-palpite': VENDAVAL_DE_PALPITE.default,
    'vice-campeao': VICE_CAMPEAO.default,
    vingativos: VINGATIVOS.default,
  };
};

/**
 * Loads a single game info by game name
 */
export const getGameInfo = async (gameName: string): Promise<GameInfo> => {
  const gameList = await getGameList();
  return gameList[gameName];
};

// Deprecated: Use getGameList() instead
// This is kept for backwards compatibility but will load all games
export default getGameList;
