/**
 * Enum of Game Phases
 */
export const PHASES: PlainObject = {
  DEFAULT: {
    LOBBY: 'LOBBY',
    RULES: 'RULES',
    SETUP: 'SETUP',
    GAME_OVER: 'GAME_OVER',
  },
  ARTE_RUIM: {
    DRAW: 'DRAW',
    EVALUATION: 'EVALUATION',
    GALLERY: 'GALLERY',
  },
  BOMBA_RELOGIO: {
    ROLE_ASSIGNMENT: 'ROLE_ASSIGNMENT',
    DECLARATION: 'DECLARATION',
    EXAMINATION: 'EXAMINATION',
    RESULT: 'RESULT',
  },
  CONTADORES_HISTORIAS: {
    STORY: 'STORY',
    CARD_PLAY: 'CARD_PLAY',
    VOTING: 'VOTING',
    RESOLUTION: 'RESOLUTION',
  },
  DETETIVES_IMAGINATIVOS: {
    SECRET_CLUE: 'SECRET_CLUE',
    CARD_PLAY: 'CARD_PLAY',
    DEFENSE: 'DEFENSE',
    VOTING: 'VOTING',
    REVEAL: 'REVEAL',
  },
  ESPIAO_ENTRE_NOS: {
    ASSIGNMENT: 'ASSIGNMENT',
    INVESTIGATION: 'INVESTIGATION',
    ASSESSMENT: 'ASSESSMENT',
    FINAL_ASSESSMENT: 'FINAL_ASSESSMENT',
    RESOLUTION: 'RESOLUTION',
  },
  DESENHO_RAPIDAO: {
    PROMPT_SELECTION: 'PROMPT_SELECTION',
    DRAWING: 'DRAWING',
    GUESSING: 'GUESSING',
    REVEAL: 'REVEAL',
  },
  GALERIA_DE_SONHOS: {
    WORD_SELECTION: 'WORD_SELECTION',
    DREAMS_SELECTION: 'DREAMS_SELECTION',
    CARD_PLAY: 'CARD_PLAY',
    RESOLUTION: 'RESOLUTION',
  },
  CRIMES_HEDIONDOS: {
    CRIME_SELECTION: 'CRIME_SELECTION',
    SCENE_MARKING: 'SCENE_MARKING',
    GUESSING: 'GUESSING',
    REVEAL: 'REVEAL',
  },
  INSTRUMENTOS_CODIFICADOS: {
    HINT_GIVING: 'HINT_GIVING',
    HINT_RECEIVING: 'HINT_RECEIVING',
    GUESS_THE_CODE: 'GUESS_THE_CODE',
    DISCUSSION: 'DISCUSSION',
    SOLUTION: 'SOLUTION',
  },
  PALHETA_DE_CORES: {
    '': '',
  },
  LINHAS_CRUZADAS: {
    PROMPT_SELECTION: 'PROMPT_SELECTION',
    DRAWING: 'DRAWING',
    NAMING: 'NAMING',
    PRESENTATION: 'PRESENTATION',
  },
  MENTE_COLETIVA: {
    QUESTION_SELECTION: 'QUESTION_SELECTION',
    EVERYBODY_WRITES: 'EVERYBODY_WRITES',
    COMPARE: 'COMPARE',
    RESOLUTION: 'RESOLUTION',
  },
  NA_RUA_DO_MEDO: {
    TRICK_OR_TREAT: 'TRICK_OR_TREAT',
    RESULT: 'RESULT',
    STREET_END: 'STREET_END',
  },
  ONDA_TELEPATICA: {
    DIAL_CLUE: 'DIAL_CLUE',
    GUESS: 'GUESS',
    REVEAL: 'REVEAL',
  },
  POLEMICA_DA_VEZ: {
    TOPIC_SELECTION: 'TOPIC_SELECTION',
    REACT: 'REACT',
    RESOLUTION: 'RESOLUTION',
  },
  QUEM_SOU_EU: {
    ASSIGNMENT: 'ASSIGNMENT',
    QUESTIONING: 'QUESTIONING',
    WHO_ARE_YOU: 'WHO_ARE_YOU',
    REVEAL: 'REVEAL',
  },
  RETRATO_FALADO: {
    COMPOSITE_SKETCH: 'COMPOSITE_SKETCH',
    EVALUATION: 'EVALUATION',
    REVEAL: 'REVEAL',
  },
  SONHOS_PESADELOS: {
    TELL_DREAM: 'TELL_DREAM',
    MATCH: 'MATCH',
    RESOLUTION: 'RESOLUTION',
    LAST_CHANCE: 'LAST_CHANCE',
  },
  TESTEMUNHA_OCULAR: {
    WITNESS_SELECTION: 'WITNESS_SELECTION',
    QUESTION_SELECTION: 'QUESTION_SELECTION',
    QUESTIONING: 'QUESTIONING',
    TRIAL: 'TRIAL',
  },
  UE_SO_ISSO: {
    WORD_SELECTION: 'WORD_SELECTION',
    SUGGEST: 'SUGGEST',
    COMPARE: 'COMPARE',
    GUESS: 'GUESS',
  },
  VENDAVAL_DE_PALPITE: {
    PROMPT_SELECTION: 'PROMPT_SELECTION',
    WRITE: 'WRITE',
    EVALUATION: 'EVALUATION',
  },
  CRUZA_PALAVRAS: {
    CLUE_WRITING: 'CLUE_WRITING',
    GUESSING: 'GUESSING',
    REVEAL: 'REVEAL',
  },
  TE_CONHECO: {
    WRITE: 'WRITE',
    TRUTHS_AND_LIES: 'TRUTHS_AND_LIES',
    RESULT: 'RESULT',
    MATCH_PLAYERS: 'MATCH_PLAYERS',
    REVEAL: 'REVEAL',
  },
};
