/**
 * Enum of Game Phases
 */
export const PHASES = {
  DEFAULT: {
    LOBBY: 'LOBBY',
    RULES: 'RULES',
    SETUP: 'SETUP',
    GAME_OVER: 'GAME_OVER',
  },
  ARTE_RUIM: {
    DRAW: 'DRAW',
    EVALUATION: 'EVALUATION',
    GALLERY: 'GALLERY',
  },
  BOMBA_RELOGIO: {
    ROLE_ASSIGNMENT: 'ROLE_ASSIGNMENT',
    DECLARATION: 'DECLARATION',
    EXAMINATION: 'EXAMINATION',
    RESULT: 'RESULT',
  },
  CAMINHOS_MAGICOS: {
    UNKNOWN: 'UNKNOWN',
  },
  CINEGRAFISTAS_AMADORES: {
    UNKNOWN: 'UNKNOWN',
  },
  CONTADORES_HISTORIAS: {
    STORY: 'STORY',
    CARD_PLAY: 'CARD_PLAY',
    VOTING: 'VOTING',
    RESOLUTION: 'RESOLUTION',
  },
  CRUZA_PALAVRAS: {
    CLUE_WRITING: 'CLUE_WRITING',
    GUESSING: 'GUESSING',
    REVEAL: 'REVEAL',
  },
  DETETIVES_IMAGINATIVOS: {
    SECRET_CLUE: 'SECRET_CLUE',
    CARD_PLAY: 'CARD_PLAY',
    DEFENSE: 'DEFENSE',
    VOTING: 'VOTING',
    REVEAL: 'REVEAL',
  },
  DILEMA_DOS_ESQUIADORES: {
    UNKNOWN: 'UNKNOWN',
  },
  ESPIAO_ENTRE_NOS: {
    ASSIGNMENT: 'ASSIGNMENT',
    INVESTIGATION: 'INVESTIGATION',
    ASSESSMENT: 'ASSESSMENT',
    FINAL_ASSESSMENT: 'FINAL_ASSESSMENT',
    RESOLUTION: 'RESOLUTION',
  },
  FILEIRA_DE_FATOS: {
    UNKNOWN: 'UNKNOWN',
  },
  GALERIA_DE_SONHOS: {
    WORD_SELECTION: 'WORD_SELECTION',
    DREAMS_SELECTION: 'DREAMS_SELECTION',
    CARD_PLAY: 'CARD_PLAY',
    RESOLUTION: 'RESOLUTION',
  },
  CRIMES_HEDIONDOS: {
    CRIME_SELECTION: 'CRIME_SELECTION',
    SCENE_MARKING: 'SCENE_MARKING',
    GUESSING: 'GUESSING',
    REVEAL: 'REVEAL',
  },
  PORTA_DOS_DESESPERADOS: {
    BOOK_POSSESSION: 'BOOK_POSSESSION',
    DOOR_CHOICE: 'DOOR_CHOICE',
    RESOLUTION: 'RESOLUTION',
  },
  INSTRUMENTOS_CODIFICADOS: {
    UNKNOWN: 'UNKNOWN',
  },
  LINHAS_CRUZADAS: {
    PROMPT_SELECTION: 'PROMPT_SELECTION',
    DRAWING: 'DRAWING',
    NAMING: 'NAMING',
    PRESENTATION: 'PRESENTATION',
  },
  MENTE_COLETIVA: {
    QUESTION_SELECTION: 'QUESTION_SELECTION',
    EVERYBODY_WRITES: 'EVERYBODY_WRITES',
    COMPARE: 'COMPARE',
    RESOLUTION: 'RESOLUTION',
  },
  NA_RUA_DO_MEDO: {
    TRICK_OR_TREAT: 'TRICK_OR_TREAT',
    RESULT: 'RESULT',
    STREET_END: 'STREET_END',
  },
  NAUFRAGOS: {
    UNKNOWN: 'UNKNOWN',
  },
  ONDA_TELEPATICA: {
    DIAL_CLUE: 'DIAL_CLUE',
    GUESS: 'GUESS',
    REVEAL: 'REVEAL',
  },
  PALHETA_DE_CORES: {
    UNKNOWN: 'UNKNOWN',
  },
  POLEMICA_DA_VEZ: {
    TOPIC_SELECTION: 'TOPIC_SELECTION',
    REACT: 'REACT',
    RESOLUTION: 'RESOLUTION',
  },
  QUEM_NAO_MATA: {
    TARGETING: 'TARGETING',
    STANDOFF: 'STANDOFF',
    DUEL: 'DUEL',
    RESOLUTION: 'RESOLUTION',
  },
  QUEM_SOU_EU: {
    ASSIGNMENT: 'ASSIGNMENT',
    QUESTIONING: 'QUESTIONING',
    WHO_ARE_YOU: 'WHO_ARE_YOU',
    REVEAL: 'REVEAL',
  },
  RETRATO_FALADO: {
    COMPOSITE_SKETCH: 'COMPOSITE_SKETCH',
    EVALUATION: 'EVALUATION',
    REVEAL: 'REVEAL',
  },
  SONHOS_PESADELOS: {
    DREAM_TELLING: 'DREAM_TELLING',
    MATCHING: 'MATCHING',
    RESOLUTION: 'RESOLUTION',
  },
  SUPER_CAMPEONATO: {
    CHALLENGE_SELECTION: 'CHALLENGE_SELECTION',
    CONTENDER_SELECTION: 'CONTENDER_SELECTION',
    BETS: 'BETS',
    BATTLE: 'BATTLE',
    RESULTS: 'RESULTS',
  },
  TESTEMUNHA_OCULAR: {
    WITNESS_SELECTION: 'WITNESS_SELECTION',
    QUESTION_SELECTION: 'QUESTION_SELECTION',
    QUESTIONING: 'QUESTIONING',
    TRIAL: 'TRIAL',
  },
  TREVO_DA_SORTE: {
    WORD_SELECTION: 'WORD_SELECTION',
    CLOVER_WRITING: 'CLOVER_WRITING',
    CLOVER_GUESSING: 'CLOVER_GUESSING',
    RESULTS: 'RESULTS',
  },
  UE_SO_ISSO: {
    WORD_SELECTION: 'WORD_SELECTION',
    SUGGEST: 'SUGGEST',
    COMPARE: 'COMPARE',
    GUESS: 'GUESS',
  },
  VENDAVAL_DE_PALPITE: {
    BOSS_SELECTION: 'BOSS_SELECTION',
    SECRET_WORD_SELECTION: 'SECRET_WORD_SELECTION',
    PLAYERS_CLUES: 'PLAYERS_CLUES',
    CLUE_EVALUATIONS: 'CLUE_EVALUATIONS',
  },
  TEMPLATE: {
    UNKNOWN: 'UNKNOWN',
  },
};
