/**
 * Enum of Game Phases
 */
export const PHASES = {
  DEFAULT: {
    LOBBY: 'LOBBY',
    RULES: 'RULES',
    SETUP: 'SETUP',
    GAME_OVER: 'GAME_OVER',
    WAIT: 'WAIT',
  },
  ADEDANHX: {
    ANSWERING: 'ANSWERING',
    EVALUATION: 'EVALUATION',
    RESULTS: 'RESULTS',
  },
  ARTE_RUIM: {
    DRAW: 'DRAW',
    EVALUATION: 'EVALUATION',
    GALLERY: 'GALLERY',
  },
  BOMBA_RELOGIO: {
    ROLE_ASSIGNMENT: 'ROLE_ASSIGNMENT',
    DECLARATION: 'DECLARATION',
    EXAMINATION: 'EXAMINATION',
    RESULT: 'RESULT',
  },
  CINEGRAFISTAS_AMADORES: {
    UNKNOWN: 'UNKNOWN',
  },
  COMUNICACAO_ALIENIGENA: {
    ALIEN_SELECTION: 'ALIEN_SELECTION',
    ALIEN_SEEDING: 'ALIEN_SEEDING',
    HUMAN_ASK: 'HUMAN_ASK',
    ALIEN_ANSWER: 'ALIEN_ANSWER',
    ALIEN_REQUEST: 'ALIEN_REQUEST',
    OFFERINGS: 'OFFERINGS',
    REVEAL: 'REVEAL',
  },
  COMUNICACAO_DUO: {
    ASKING_FOR_SOMETHING: 'ASKING_FOR_SOMETHING',
    DELIVER_SOMETHING: 'DELIVER_SOMETHING',
    VERIFICATION: 'VERIFICATION',
  },
  CONTADORES_HISTORIAS: {
    STORY: 'STORY',
    CARD_PLAY: 'CARD_PLAY',
    VOTING: 'VOTING',
    RESOLUTION: 'RESOLUTION',
  },
  CONTROLE_DE_ESTOQUE: {
    // PHASE ONE
    GOOD_PLACEMENT: 'GOOD_PLACEMENT',
    PLACEMENT_CONFIRMATION: 'PLACEMENT_CONFIRMATION',
    // PHASE TWO
    FULFILLMENT: 'FULFILLMENT',
    RESULTS: 'RESULTS',
  },
  CRUZA_PALAVRAS: {
    WORDS_SELECTION: 'WORDS_SELECTION',
    CLUE_WRITING: 'CLUE_WRITING',
    GUESSING: 'GUESSING',
    REVEAL: 'REVEAL',
  },
  DETETIVES_IMAGINATIVOS: {
    SECRET_CLUE: 'SECRET_CLUE',
    CARD_PLAY: 'CARD_PLAY',
    DEFENSE: 'DEFENSE',
    VOTING: 'VOTING',
    REVEAL: 'REVEAL',
  },
  ESQUIADORES: {
    UNKNOWN: 'UNKNOWN',
  },
  DUETOS: {
    PAIRING: 'PAIRING',
    RESULTS: 'RESULTS',
  },
  ESPIAO_ENTRE_NOS: {
    ASSIGNMENT: 'ASSIGNMENT',
    INVESTIGATION: 'INVESTIGATION',
    ASSESSMENT: 'ASSESSMENT',
    FINAL_ASSESSMENT: 'FINAL_ASSESSMENT',
    RESOLUTION: 'RESOLUTION',
  },
  FILEIRA_DE_FATOS: {
    ORDERING: 'ORDERING',
    RESULTS: 'RESULTS',
  },
  GALERIA_DE_SONHOS: {
    WORD_SELECTION: 'WORD_SELECTION',
    DREAMS_SELECTION: 'DREAMS_SELECTION',
    CARD_PLAY: 'CARD_PLAY',
    RESOLUTION: 'RESOLUTION',
  },
  CRIMES_HEDIONDOS: {
    CRIME_SELECTION: 'CRIME_SELECTION',
    SCENE_MARKING: 'SCENE_MARKING',
    GUESSING: 'GUESSING',
    REVEAL: 'REVEAL',
  },
  INSTRUMENTOS_CODIFICADOS: {
    UNKNOWN: 'UNKNOWN',
  },
  LABIRINTO_SECRETO: {
    MAP_BUILDING: 'MAP_BUILDING',
    PATH_FOLLOWING: 'PATH_FOLLOWING',
    RESULTS: 'RESULTS',
  },
  LINHAS_CRUZADAS: {
    PROMPT_SELECTION: 'PROMPT_SELECTION',
    DRAWING: 'DRAWING',
    NAMING: 'NAMING',
    PRESENTATION: 'PRESENTATION',
  },
  MEGAMIX: {
    SEEDING: 'SEEDING',
    TRACK: 'TRACK',
    RESULT: 'RESULT',
  },
  MENTE_COLETIVA: {
    QUESTION_SELECTION: 'QUESTION_SELECTION',
    EVERYBODY_WRITES: 'EVERYBODY_WRITES',
    COMPARE: 'COMPARE',
    RESOLUTION: 'RESOLUTION',
  },
  MESMICE: {
    CLUE_WRITING: 'CLUE_WRITING',
    OBJECT_FEATURE_ELIMINATION: 'OBJECT_FEATURE_ELIMINATION',
    RESULT: 'RESULT',
  },
  NA_RUA_DO_MEDO: {
    TRICK_OR_TREAT: 'TRICK_OR_TREAT',
    RESULT: 'RESULT',
    STREET_END: 'STREET_END',
  },
  NAO_SOU_ROBO: {
    CARD_SELECTION: 'CARD_SELECTION',
    ARE_YOU_A_ROBOT: 'ARE_YOU_A_ROBOT',
    RESULTS: 'RESULTS',
  },
  NAUFRAGOS: {
    UNKNOWN: 'UNKNOWN',
  },
  ONDA_TELEPATICA: {
    DIAL_CLUE: 'DIAL_CLUE',
    GUESS: 'GUESS',
    REVEAL: 'REVEAL',
  },
  PALHETA_DE_CORES: {
    UNKNOWN: 'UNKNOWN',
  },
  PLANEJAMENTO_URBANO: {
    PLANNING: 'PLANNING',
    PLACING: 'PLACING',
    RESOLUTION: 'RESOLUTION',
  },
  POLEMICA_DA_VEZ: {
    TOPIC_SELECTION: 'TOPIC_SELECTION',
    REACT: 'REACT',
    RESOLUTION: 'RESOLUTION',
  },
  PORTA_DOS_DESESPERADOS: {
    BOOK_POSSESSION: 'BOOK_POSSESSION',
    DOOR_CHOICE: 'DOOR_CHOICE',
    RESOLUTION: 'RESOLUTION',
  },
  QUEM_NAO_MATA: {
    TARGETING: 'TARGETING',
    STANDOFF: 'STANDOFF',
    DUEL: 'DUEL',
    RESOLUTION: 'RESOLUTION',
  },
  QUEM_SOU_EU: {
    CHARACTER_FILTERING: 'CHARACTER_FILTERING',
    CHARACTER_DESCRIPTION: 'CHARACTER_DESCRIPTION',
    GUESSING: 'GUESSING',
    RESULTS: 'RESULTS',
  },
  RETRATO_FALADO: {
    COMPOSITE_SKETCH: 'COMPOSITE_SKETCH',
    EVALUATION: 'EVALUATION',
    REVEAL: 'REVEAL',
  },
  SINAIS_DE_ALERTA: {
    DRAWING: 'DRAWING',
    EVALUATION: 'EVALUATION',
    GALLERY: 'GALLERY',
  },
  SONHOS_PESADELOS: {
    DREAM_TELLING: 'DREAM_TELLING',
    MATCHING: 'MATCHING',
    RESOLUTION: 'RESOLUTION',
  },
  SUPER_CAMPEONATO: {
    CHALLENGE_SELECTION: 'CHALLENGE_SELECTION',
    CONTENDER_SELECTION: 'CONTENDER_SELECTION',
    BETS: 'BETS',
    BATTLE: 'BATTLE',
    RESULTS: 'RESULTS',
  },
  TA_NA_CARA: {
    PROMPT: 'PROMPT',
    ANSWERING: 'ANSWERING',
    GUESSING: 'GUESSING',
    REVEAL: 'REVEAL',
  },
  TEORIA_DE_CONJUNTOS: {
    JUDGE_SELECTION: 'JUDGE_SELECTION',
    ITEM_PLACEMENT: 'ITEM_PLACEMENT',
    EVALUATION: 'EVALUATION',
    REVEAL: 'REVEAL',
  },
  TESTEMUNHA_OCULAR: {
    WITNESS_SELECTION: 'WITNESS_SELECTION',
    QUESTION_SELECTION: 'QUESTION_SELECTION',
    QUESTIONING: 'QUESTIONING',
    TRIAL: 'TRIAL',
  },
  TESTE_DE_ELENCO: {
    MOVIE_GENRE_SELECTION: 'MOVIE_GENRE_SELECTION',
    ACTOR_SELECTION: 'ACTOR_SELECTION',
    RESULT: 'RESULT',
  },
  TREVO_DA_SORTE: {
    WORD_SELECTION: 'WORD_SELECTION',
    CLOVER_WRITING: 'CLOVER_WRITING',
    CLOVER_GUESSING: 'CLOVER_GUESSING',
    RESULTS: 'RESULTS',
  },
  UE_SO_ISSO: {
    WORD_SELECTION: 'WORD_SELECTION',
    SUGGEST: 'SUGGEST',
    COMPARE: 'COMPARE',
    GUESS: 'GUESS',
    VERIFY_GUESS: 'VERIFY_GUESS',
    RESULT: 'RESULT',
  },
  VAMOS_AO_CINEMA: {
    MOVIE_SELECTION: 'MOVIE_SELECTION',
    MOVIE_ELIMINATION: 'MOVIE_ELIMINATION',
    REVEAL: 'REVEAL',
  },
  VENDAVAL_DE_PALPITE: {
    BOSS_SELECTION: 'BOSS_SELECTION',
    SECRET_WORD_SELECTION: 'SECRET_WORD_SELECTION',
    PLAYERS_CLUES: 'PLAYERS_CLUES',
    CLUE_EVALUATIONS: 'CLUE_EVALUATIONS',
  },
  VINGATIVOS: {
    UNKNOWN: 'UNKNOWN',
  },
  TEMPLATE: {
    UNKNOWN: 'UNKNOWN',
  },
};
