export const TESTE_DE_ELENCO_PHASES = {
  MOVIE_GENRE_SELECTION: 'MOVIE_GENRE_SELECTION',
  ACTOR_SELECTION: 'ACTOR_SELECTION',
  RESULT: 'RESULT',
} as const;

export const TESTE_DE_ELENCO_ACTIONS = {
  SELECT_MOVIE_GENRE: 'SELECT_MOVIE_GENRE',
  SELECT_ACTOR: 'SELECT_ACTOR',
} as const;
