export const TEORIA_DE_CONJUNTOS_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  JUDGE_SELECTION: 'JUDGE_SELECTION',
  ITEM_PLACEMENT: 'ITEM_PLACEMENT',
  EVALUATION: 'EVALUATION',
  REVEAL: 'REVEAL',
  GAME_OVER: 'GAME_OVER',
};

export const TEORIA_DE_CONJUNTOS_ACTIONS = {
  SUBMIT_JUDGE: 'SUBMIT_JUDGE',
  SUBMIT_ITEM_PLACEMENT: 'SUBMIT_ITEM_PLACEMENT',
  SUBMIT_EVALUATION: 'SUBMIT_EVALUATION',
};

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 10,
};

export const TEORIA_DE_CONJUNTOS_ACHIEVEMENTS = {
  MOST_ATTRIBUTE_CIRCLE: 'MOST_ATTRIBUTE_CIRCLE',
  MOST_WORD_CIRCLE: 'MOST_WORD_CIRCLE',
  MOST_CONTEXT_CIRCLE: 'MOST_CONTEXT_CIRCLE',
  MOST_OUTSIDE: 'MOST_OUTSIDE',
  MOST_INTERSECTIONS: 'MOST_INTERSECTIONS',
  THE_JUDGE: 'THE_JUDGE',
  MOST_WRONG: 'MOST_WRONG',
};

export const MAX_ROUNDS = 30;

export const ROUNDS_PER_PLAYER = 5;

export const STARTING_ITEMS_PER_PLAYER_COUNT = {
  2: 10,
  3: 7,
  4: 5,
  5: 5,
  6: 4,
  7: 4,
  8: 4,
  9: 3,
  10: 3,
};

export const OUTCOME = {
  CONTINUE: 'CONTINUE',
  WRONG: 'WRONG',
  PENDING: 'PENDING',
  WIN: 'WIN',
};
