export const TEORIA_DE_CONJUNTOS_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  JUDGE_SELECTION: 'JUDGE_SELECTION',
  DIAGRAM_PLACEMENT: 'DIAGRAM_PLACEMENT',
  EVALUATION: 'EVALUATION',
  REVEAL: 'REVEAL',
  GAME_OVER: 'GAME_OVER',
};

export const TEORIA_DE_CONJUNTOS_ACTIONS = {
  SUBMIT_JUDGE: 'SUBMIT_JUDGE',
  SUBMIT_ITEM_DIAGRAM: 'SUBMIT_ITEM_DIAGRAM',
  SUBMIT_EVALUATION: 'SUBMIT_EVALUATION',
};

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 10,
};

export const TEORIA_DE_CONJUNTOS_ACHIEVEMENTS = {};

export const MAX_ROUNDS = 10;

export const STARTING_ITEMS_PER_PLAYER_COUNT = {
  2: 5,
  3: 5,
  4: 5,
  5: 4,
  6: 4,
  7: 3,
  8: 3,
  9: 3,
  10: 3,
};

export const OUTCOME = {
  CONTINUE: 'CONTINUE',
  WRONG: 'WRONG',
  PENDING: 'PENDING',
  WIN: 'WIN',
};
