export const QUEM_SOU_EU_PHASES = {
  CHARACTER_FILTERING: 'CHARACTER_FILTERING',
  CHARACTER_DESCRIPTION: 'CHARACTER_DESCRIPTION',
  GUESSING: 'GUESSING',
  RESULTS: 'RESULTS',
} as const;

export const QUEM_SOU_EU_ACTIONS = {
  SUBMIT_CHARACTERS: 'SUBMIT_CHARACTERS',
  SUBMIT_GLYPHS: 'SUBMIT_GLYPHS',
  SUBMIT_GUESSES: 'SUBMIT_GUESSES',
} as const;

export const SLIDE_DURATION = 10;

export const ROUND_TYPE = {
  SHOW: 'SHOW',
  HIDE: 'HIDE',
} as const;
