export const QUAL_QUESITO_PHASES = {
  LOBBY: 'LOBBY',
  SETUP: 'SETUP',
  CATEGORY_CREATION: 'CATEGORY_CREATION',
  SKIP_ANNOUNCEMENT: 'SKIP_ANNOUNCEMENT',
  CARD_PLAY: 'CARD_PLAY',
  VERIFICATION: 'VERIFICATION',
  RESULTS: 'RESULTS',
  GAME_OVER: 'GAME_OVER',
} as const;

export const QUAL_QUESITO_ACTIONS = {
  SUBMIT_CATEGORY: 'SUBMIT_CATEGORY',
  SKIP_TURN: 'SKIP_TURN',
  SUBMIT_CARDS: 'SUBMIT_CARDS',
  SUBMIT_EVALUATIONS: 'SUBMIT_EVALUATIONS',
} as const;

export const QUAL_QUESITO_ACHIEVEMENTS = {
  MOST_CREATOR_EXTRA_CARDS: 'MOST_CREATOR_EXTRA_CARDS',
  MOST_PARTICIPATION: 'MOST_PARTICIPATION',
  LEAST_PARTICIPATION: 'LEAST_PARTICIPATION',
  MOST_REJECTIONS: 'MOST_REJECTIONS',
  FEWEST_REJECTIONS: 'FEWEST_REJECTIONS',
  BEST_CREATOR: 'BEST_CREATOR', // fewest participation on creator turns
  WORST_CREATOR: 'WORST_CREATOR', // most participation on creator turns
  MOST_SKIPS: 'MOST_SKIPS',
  MOST_ACCEPTING: 'MOST_ACCEPTING',
  MOST_DECLINING: 'MOST_DECLINING',
};

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 10,
} as const;

export const TOTAL_ROUNDS = 15;

export const CARDS_PER_PLAYER = 9;
export const DECK_PER_PLAYER = 10;

export const CREATOR_SCORE_POINTS = 2;
export const OTHERS_SCORE_POINTS = 3;
export const CREATOR_SCORE_BONUS = 1;
export const CONSECUTIVE_REJECTION_PENALTY = -1;
export const EMPTY_HAND_BONUS = 3;
