export const COMUNICACAO_DUO_PHASES = {
  ASKING_FOR_SOMETHING: 'ASKING_FOR_SOMETHING',
  DELIVER_SOMETHING: 'DELIVER_SOMETHING',
  VERIFICATION: 'VERIFICATION',
} as const;

export const COMUNICACAO_DUO_ACTIONS = {
  SUBMIT_REQUEST: 'SUBMIT_REQUEST',
  SUBMIT_DELIVERY: 'SUBMIT_DELIVERY',
  STOP_DELIVERY: 'STOP_DELIVERY',
};

export const TOTAL_ITEMS = 16;

export const AFFILIATIONS = {
  A: 'A',
  B: 'B',
  TABOO: 'TABOO',
  NONE: 'NONE',
};

export const SIDES = [AFFILIATIONS.A, AFFILIATIONS.B];

export const STATUS = {
  IDLE: 'IDLE',
  WIN: 'WIN',
  LOSE: 'LOSE',
  CONTINUE: 'CONTINUE',
};

export const DECK_ENTRY_STATUS = {
  IDLE: 'IDLE',
  A: AFFILIATIONS.A,
  B: AFFILIATIONS.B,
  NONE: AFFILIATIONS.NONE,
  TABOO: AFFILIATIONS.TABOO,
};
