export const GALERIA_DE_SONHOS_PHASES = {
  SETUP: 'SETUP',
  WORD_SELECTION: 'WORD_SELECTION',
  DREAMS_SELECTION: 'DREAMS_SELECTION',
  CARD_PLAY: 'CARD_PLAY',
  RESOLUTION: 'RESOLUTION',
  GAME_OVER: 'GAME_OVER',
} as const;

export const GALERIA_DE_SONHOS_ACTIONS = {
  SUBMIT_WORD: 'SUBMIT_WORD',
  SUBMIT_CARDS: 'SUBMIT_CARDS',
  PLAY_CARD: 'PLAY_CARD',
} as const;

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 10,
} as const;

export const TOTAL_ROUNDS = 4;

export const TABLE_DECK_TOTAL = 30;

export const WORD_DECK_TOTAL = 10;

export const INITIAL_TABLE_SIZE = 15;
