export const ESQUIADORES_PHASES = {
  LOBBY: 'LOBBY',
  SETUP: 'SETUP',
  BETS: 'BETS',
  STARTING_RESULTS: 'STARTING_RESULTS',
  BOOSTS: 'BOOSTS',
  PRELIMINARY_RESULTS: 'PRELIMINARY_RESULTS',
  LAST_CHANGE: 'LAST_CHANGE',
  FINAL_RESULTS: 'FINAL_RESULTS',
  GAME_OVER: 'GAME_OVER',
};

export const ESQUIADORES_ACTIONS = {
  SUBMIT_CHOICES: 'SUBMIT_CHOICES',
  SUBMIT_BETS: 'SUBMIT_BETS',
};

export const ESQUIADORES_ACHIEVEMENTS = {
  MOST_LODGES: 'MOST_LODGES',
  FEWEST_LODGES: 'FEWEST_LODGES',
  MOST_GROUP_BETS: 'MOST_GROUP_BETS',
  FEWEST_GROUP_BETS: 'FEWEST_GROUP_BETS',
  MOST_GROUP_INITIAL_BETS: 'MOST_GROUP_INITIAL_BETS',
  FEWEST_GROUP_INITIAL_BETS: 'FEWEST_GROUP_INITIAL_BETS',
  MOST_GROUP_BOOST_BETS: 'MOST_GROUP_BOOST_BETS',
  FEWEST_GROUP_BOOST_BETS: 'FEWEST_GROUP_BOOST_BETS',
  MOST_GROUP_FINAL_BETS: 'MOST_GROUP_FINAL_BETS',
  FEWEST_GROUP_FINAL_BETS: 'FEWEST_GROUP_FINAL_BETS',
  ONLY_LODGE: 'ONLY_LODGE',
  MOST_PLAYER_BETS: 'MOST_PLAYER_BETS',
  FEWEST_PLAYER_BETS: 'FEWEST_PLAYER_BETS',
  HIGHEST_BET: 'HIGHEST_BET',
  MOST_BET_ON_PLAYER: 'MOST_BET_ON_PLAYER',
  LEAST_BET_ON_PLAYER: 'LEAST_BET_ON_PLAYER',
};

export const PLAYER_COUNTS = {
  MIN: 3,
  MAX: 10,
};

export const MAX_ROUNDS = 10;

export const DOUBLE_ROUNDS_THRESHOLD = 4;

export const DILEMMAS_PER_ROUND = 6;

export const BETTING_CHIPS = {
  INITIAL: 5,
  BOOST: 3,
  FINAL: 2,
};

export const SKIERS_BETTING_CHIPS = {
  INITIAL: 0,
  BOOST: 7,
  FINAL: 3,
};

export const CATCH_UP_BONUS = 2;

export const BET_TYPES = {
  INITIAL: 'initial',
  BOOST: 'boost',
  FINAL: 'final',
};

export const SKIER_BET_TYPES = {
  SKIERS_BETS: 'skiersBets',
  SKIERS_BOOST: 'skiersBoost',
};

export const MOUNTAIN_SECTION = {
  SUMMIT: 'SUBMIT', // nothing is display
  LEVEL_1: 'LEVEL_1', // after first decision
  LEVEL_2: 'LEVEL_2', // after second decision
  LODGE: 'LODGE', // after final decision
} as const;
