export const CRUZA_PALAVRAS_PHASES = {
  LOBBY: 'LOBBY',
  SETUP: 'SETUP',
  WORDS_SELECTION: 'WORDS_SELECTION',
  CLUE_WRITING: 'CLUE_WRITING',
  GUESSING: 'GUESSING',
  REVEAL: 'REVEAL',
  GAME_OVER: 'GAME_OVER',
};

export const CRUZA_PALAVRAS_ACTIONS = {
  SUBMIT_WORDS: 'SUBMIT_WORDS',
  SUBMIT_CLUE: 'SUBMIT_CLUE',
  SUBMIT_GUESSES: 'SUBMIT_GUESSES',
};

export const CRUZA_PALAVRAS_ACHIEVEMENTS = {
  BEST_CLUES: 'BEST_CLUES',
  WORST_CLUES: 'WORST_CLUES',
  BEST_GUESSER: 'BEST_GUESSER',
  WORST_GUESSER: 'WORST_GUESSER',
  CHOOSE_FOR_ME: 'CHOOSE_FOR_ME',
  SHORTEST_WORDS: 'SHORTEST_WORDS',
  LONGEST_WORDS: 'LONGEST_WORDS',
  SAVIOR: 'SAVIOR',
};

export const PLAYER_COUNTS = {
  MIN: 3,
  MAX: 8,
};

export const TOTAL_ROUNDS = 6;

export const WORDS_PER_COORDINATE = {
  3: 4,
  4: 4,
  5: 5,
  6: 5,
  7: 6,
  8: 6,
};
