export const SONHOS_PESADELOS_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  DREAM_TELLING: 'DREAM_TELLING',
  MATCHING: 'MATCHING',
  RESOLUTION: 'RESOLUTION',
  GAME_OVER: 'GAME_OVER',
};

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 10,
};

export const TOTAL_ROUNDS = 5;

export const IMAGE_CARDS_PER_ROUND = 6;

export const THEMES_PER_ROUND = 3;
