export const QUAL_QUESITO_PHASES = {
  CATEGORY_CREATION: 'CATEGORY_CREATION',
  SKIP_ANNOUNCEMENT: 'SKIP_ANNOUNCEMENT',
  CARD_PLAY: 'CARD_PLAY',
  VERIFICATION: 'VERIFICATION',
  RESULTS: 'RESULTS',
} as const;

export const QUAL_QUESITO_ACTIONS = {
  SUBMIT_CATEGORY: 'SUBMIT_CATEGORY',
  SKIP_TURN: 'SKIP_TURN',
  SUBMIT_CARDS: 'SUBMIT_CARDS',
  SUBMIT_EVALUATIONS: 'SUBMIT_EVALUATIONS',
} as const;

export const CREATOR_SCORE_POINTS = 2;
export const OTHERS_SCORE_POINTS = 3;
export const CREATOR_SCORE_BONUS = 1;
export const CONSECUTIVE_REJECTION_PENALTY = -1;
