export const ESPIAO_ENTRE_NOS_PHASES = {
  ASSIGNMENT: 'ASSIGNMENT',
  INVESTIGATION: 'INVESTIGATION',
  ASSESSMENT: 'ASSESSMENT',
  FINAL_ASSESSMENT: 'FINAL_ASSESSMENT',
  RESOLUTION: 'RESOLUTION',
} as const;

export const ESPIAO_ENTRE_NOS_ACTIONS = {
  LAST_QUESTIONER: 'LAST_QUESTIONER',
  MAKE_ACCUSATION: 'MAKE_ACCUSATION',
  SUBMIT_VOTE: 'SUBMIT_VOTE',
  GUESS_LOCATION: 'GUESS_LOCATION',
} as const;
