export const RETRATO_FALADO_PHASES = {
  LOBBY: 'LOBBY',
  SETUP: 'SETUP',
  COMPOSITE_SKETCH: 'COMPOSITE_SKETCH',
  EVALUATION: 'EVALUATION',
  REVEAL: 'REVEAL',
  GAME_OVER: 'GAME_OVER',
};

export const RETRATO_FALADO_ACTIONS = {
  SUBMIT_ORIENTATION: 'SUBMIT_ORIENTATION',
  SUBMIT_SKETCH: 'SUBMIT_SKETCH',
  SUBMIT_VOTE: 'SUBMIT_VOTE',
};

export const RETRATO_FALADO_ACHIEVEMENTS = {
  BEST_SKETCHES: 'BEST_SKETCHES',
  WORST_SKETCHES: 'WORST_SKETCHES',
  MOST_GROUP_VOTES: 'MOST_GROUP_VOTES',
  FEWEST_GROUP_VOTES: 'FEWEST_GROUP_VOTES',
  WITNESS_PICK: 'WITNESS_PICK',
};

export const PLAYER_COUNTS = {
  MIN: 4,
  MAX: 10,
};

export const MAX_ROUNDS = 10;
