export const SINAIS_DE_ALERTA_PHASES = {
  DRAWING: 'DRAWING',
  EVALUATION: 'EVALUATION',
  GALLERY: 'GALLERY',
} as const;

export const SINAIS_DE_ALERTA_ACTIONS = {
  SUBMIT_DRAWING: 'SUBMIT_DRAWING',
  SUBMIT_EVALUATION: 'SUBMIT_EVALUATION',
} as const;

export const SLIDE_DURATION = 7;
