export const ADEDANHX_PHASES = {
  ANSWERING: 'ANSWERING',
  EVALUATION: 'EVALUATION',
  RESULTS: 'RESULTS',
} as const;

export const ADEDANHX_ACTIONS = {
  SUBMIT_ANSWERS: 'SUBMIT_ANSWERS',
  SUBMIT_EVALUATIONS: 'SUBMIT_EVALUATIONS',
} as const;

export const ANSWERING_TIME = 180;

export const ANSWERING_TIME_IN_MINUTES = ANSWERING_TIME / 60;
