export const ADEDANHX_PHASES = {
  ANSWERING: 'ANSWERING',
  EVALUATION: 'EVALUATION',
  RESULTS: 'RESULTS',
} as const;

export const ADEDANHX_ACTIONS = {
  SUBMIT_ANSWERS: 'SUBMIT_ANSWERS',
  NEXT_EVALUATION_GROUP: 'NEXT_EVALUATION_GROUP',
  SUBMIT_REJECTED_ANSWERS: 'SUBMIT_REJECTED_ANSWERS',
} as const;

export const ANSWERING_TIME = 180;

export const ANSWERING_TIME_IN_MINUTES = ANSWERING_TIME / 60;
