export const SENSO_LITERARIO_PHASES = {
  LOBBY: 'LOBBY',
  SETUP: 'SETUP',
  PATTERN_CREATION: 'PATTERN_CREATION',
  RESULT: 'RESULT',
  GAME_OVER: 'GAME_OVER',
};

export const SENSO_LITERARIO_ACTIONS = {
  SUBMIT_PATTERN: 'SUBMIT_PATTERN',
};

export const SENSO_LITERARIO_ACHIEVEMENTS = {
  MOST_CHILDRENS_BOOKS_MATCHES: 'MOST_CHILDRENS_BOOKS_MATCHES',
  MOST_ROMANCE_BOOKS_MATCHES: 'MOST_ROMANCE_BOOKS_MATCHES',
  MOST_TECHNICAL_BOOKS_MATCHES: 'MOST_TECHNICAL_BOOKS_MATCHES',
  MOST_RED_BOOKS_MATCHES: 'MOST_RED_BOOKS_MATCHES',
  MOST_BLUE_BOOKS_MATCHES: 'MOST_BLUE_BOOKS_MATCHES',
  MOST_YELLOW_BOOKS_MATCHES: 'MOST_YELLOW_BOOKS_MATCHES',
  MOST_LETTER_A_BOOKS_MATCHES: 'MOST_LETTER_A_BOOKS_MATCHES',
  MOST_LETTER_B_BOOKS_MATCHES: 'MOST_LETTER_B_BOOKS_MATCHES',
  MOST_LETTER_C_BOOKS_MATCHES: 'MOST_LETTER_C_BOOKS_MATCHES',
  MOST_LETTER_D_BOOKS_MATCHES: 'MOST_LETTER_D_BOOKS_MATCHES',
  MOST_LETTER_E_BOOKS_MATCHES: 'MOST_LETTER_E_BOOKS_MATCHES',
  MOST_NO_MATCHES: 'MOST_NO_MATCHES',
  MOST_FULL_MATCHES: 'MOST_FULL_MATCHES',
  FEWEST_FULL_MATCHES: 'FEWEST_FULL_MATCHES',
};

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 6,
};

export const TOTAL_ROUNDS = 5;

export const GENRES = ['childrens', 'romance', 'technical'];
export const COLORS = ['red', 'blue', 'yellow'];
export const LETTERS = ['A', 'B', 'C', 'D', 'E'];

export const POINTS_PER_GUESS = 1;
export const BONUS_POINT_FOR_SET = 1;
