export const MENTE_COLETIVA_PHASES = {
  QUESTION_SELECTION: 'QUESTION_SELECTION',
  EVERYBODY_WRITES: 'EVERYBODY_WRITES',
  COMPARE: 'COMPARE',
  RESOLUTION: 'RESOLUTION',
} as const;

export const MENTE_COLETIVA_ACTIONS = {
  SUBMIT_QUESTION: 'SUBMIT_QUESTION',
  SUBMIT_CUSTOM_QUESTION: 'SUBMIT_CUSTOM_QUESTION',
  SUBMIT_ANSWERS: 'SUBMIT_ANSWERS',
  NEXT_ANSWERS: 'NEXT_ANSWERS',
  ADD_ANSWER: 'ADD_ANSWER',
} as const;
