export const MEDIDAS_NAO_EXATAS_PHASES = {
  LOBBY: 'LOBBY',
  SETUP: 'SETUP',
  METRICS_BUILDING: 'METRICS_BUILDING',
  GUESSING: 'GUESSING',
  RESULTS: 'RESULTS',
  GAME_OVER: 'GAME_OVER',
} as const;

export const MEDIDAS_NAO_EXATAS_ACTIONS = {
  SUBMIT_POOL: 'SUBMIT_POOL',
  SUBMIT_METRICS: 'SUBMIT_METRICS',
  SUBMIT_GUESS: 'SUBMIT_GUESS',
} as const;

export const MEDIDAS_NAO_EXATAS_ACHIEVEMENTS = {
  MOST_DOUBLE_GUESSES: 'MOST_DOUBLE_GUESSES',
  FEWEST_DOUBLE_GUESSES: 'FEWEST_DOUBLE_GUESSES',
  WORST_METRICS: 'WORST_METRICS',
  BEST_METRICS: 'BEST_METRICS',
  MOST_LEVEL_1_GUESSES: 'MOST_LEVEL_1_GUESSES',
  MOST_LEVEL_2_GUESSES: 'MOST_LEVEL_2_GUESSES',
  MOST_LEVEL_3_GUESSES: 'MOST_LEVEL_3_GUESSES',
  MOST_LEVEL_4_GUESSES: 'MOST_LEVEL_4_GUESSES',
  MOST_LEVEL_5_GUESSES: 'MOST_LEVEL_5_GUESSES',
};

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 10,
} as const;

export const TOTAL_ROUNDS = 5;

export const WORDS_PER_PLAYER = 8;
export const DESCRIPTORS_PER_PLAYER = 10;
