export const QUEM_NAO_MATA_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  TARGETING: 'TARGETING',
  STANDOFF: 'STANDOFF',
  DUEL: 'DUEL',
  RESOLUTION: 'RESOLUTION',
  GAME_OVER: 'GAME_OVER',
};

export const QUEM_NAO_MATA_ACTIONS = {
  SUBMIT_TARGET: 'SUBMIT_TARGET',
  SUBMIT_MESSAGE: 'SUBMIT_MESSAGE',
  SUBMIT_DECISION: 'SUBMIT_DECISION',
};

export const PLAYER_COUNTS = {
  MIN: 4,
  MAX: 10,
};

export const MAX_ROUNDS = 10;
