export const OUTCOME = {
  CONTINUE: 'CONTINUE',
  TOO_SUSPICIOUS: 'TOO_SUSPICIOUS',
  ROBOT_WINS: 'ROBOT_WINS',
  HUMANS_WIN: 'HUMANS_WIN',
};

export const SUSPICION_THRESHOLD = 3;

export const BEAT_THRESHOLD = 3;
