export const FILEIRA_DE_FATOS_PHASES = {
  LOBBY: 'LOBBY',
  SETUP: 'SETUP',
  ORDERING: 'ORDERING',
  RESULTS: 'RESULTS',
  GAME_OVER: 'GAME_OVER',
};

export const FILEIRA_DE_FATOS_ACTIONS = {
  SUBMIT_SCENARIO_ORDER: 'SUBMIT_SCENARIO_ORDER',
};

export const FILEIRA_DE_FATOS_ACHIEVEMENTS = {
  MOST_FIRST_POSITIONS: 'MOST_FIRST_POSITIONS',
  FEWEST_FIRST_POSITIONS: 'FEWEST_FIRST_POSITIONS',
  MOST_SECOND_POSITIONS: 'MOST_SECOND_POSITIONS',
  FEWEST_SECOND_POSITIONS: 'FEWEST_SECOND_POSITIONS',
  MOST_THIRD_POSITIONS: 'MOST_THIRD_POSITIONS',
  FEWEST_THIRD_POSITIONS: 'FEWEST_THIRD_POSITIONS',
  MOST_FOURTH_POSITIONS: 'MOST_FOURTH_POSITIONS',
  FEWEST_FOURTH_POSITIONS: 'FEWEST_FOURTH_POSITIONS',
  MOST_FIFTH_POSITIONS: 'MOST_FIFTH_POSITIONS',
  FEWEST_FIFTH_POSITIONS: 'FEWEST_FIFTH_POSITIONS',
  BEST_COMMON_SENSE: 'BEST_COMMON_SENSE',
  WORST_COMMON_SENSE: 'WORST_COMMON_SENSE',
  PERFECT_GUESS: 'PERFECT_GUESS',
};

export const PLAYER_COUNTS = {
  MIN: 3,
  MAX: 12,
};

export const MAX_ROUNDS = 12;

export const SCENARIOS_PER_ROUND = 5;

export const ROUND_TYPES = [
  // Normal indicates 1 point per correct guess
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  // 3 points of the correct second position
  'SECOND_POSITION',
  // 3 points of the correct forth position
  'FOURTH_POSITION',
  // 3 points of the correct center position
  'CENTER_POSITION',
  // -1 point if first position is wrong
  'CURSED_FIRST_POSITION',
  // -1 point if last position is wrong
  'CURSED_LAST_POSITION',
];
