export const MENTE_COLETIVA_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  QUESTION_SELECTION: 'QUESTION_SELECTION',
  EVERYBODY_WRITES: 'EVERYBODY_WRITES',
  COMPARE: 'COMPARE',
  RESOLUTION: 'RESOLUTION',
  GAME_OVER: 'GAME_OVER',
};

export const PLAYER_COUNT = {
  MIN: 3,
  MAX: 12,
};

export const MAX_ROUNDS = 15;

export const QUESTIONS_PER_ROUND = 3;

export const PASTURE_GAME_OVER_THRESHOLD = 5;

export const ROUND_TYPES = {
  0: 'ONE_IN_ONE_OUT',
  1: 'ONE_OUT',
  2: 'TWO_OUT',
  3: 'THREE_OUT',
};
