export const MENTE_COLETIVA_PHASES = {
  SETUP: 'SETUP',
  QUESTION_SELECTION: 'QUESTION_SELECTION',
  EVERYBODY_WRITES: 'EVERYBODY_WRITES',
  COMPARE: 'COMPARE',
  RESOLUTION: 'RESOLUTION',
  GAME_OVER: 'GAME_OVER',
} as const;

export const MENTE_COLETIVA_ACTIONS = {
  SUBMIT_QUESTION: 'SUBMIT_QUESTION',
  SUBMIT_CUSTOM_QUESTION: 'SUBMIT_CUSTOM_QUESTION',
  SUBMIT_ANSWERS: 'SUBMIT_ANSWERS',
  NEXT_ANSWERS: 'NEXT_ANSWERS',
  ADD_ANSWER: 'ADD_ANSWER',
} as const;

export const PLAYER_COUNTS = {
  MIN: 3,
  MAX: 12,
} as const;

export const MAX_ROUNDS = 15;

export const QUESTIONS_PER_ROUND = 3;

export const PASTURE_GAME_OVER_THRESHOLD = 5;

export const SHORT_PASTURE_GAME_OVER_THRESHOLD = 3;

export const ROUND_TYPES = {
  0: 'ONE_IN_ONE_OUT',
  1: 'ONE_OUT',
  2: 'TWO_OUT',
  3: 'THREE_OUT',
};
