export const TESTEMUNHA_OCULAR_PHASES = {
  WITNESS_SELECTION: 'WITNESS_SELECTION',
  QUESTION_SELECTION: 'QUESTION_SELECTION',
  QUESTIONING: 'QUESTIONING',
  TRIAL: 'TRIAL',
} as const;

export const TESTEMUNHA_OCULAR_ACTIONS = {
  SELECT_WITNESS: 'SELECT_WITNESS',
  SELECT_QUESTION: 'SELECT_QUESTION',
  GIVE_TESTIMONY: 'GIVE_TESTIMONY',
  ELIMINATE_SUSPECT: 'ELIMINATE_SUSPECT',
} as const;
