export const TESTEMUNHA_OCULAR_ACTIONS = {
  SELECT_WITNESS: 'SELECT_WITNESS',
  SELECT_QUESTION: 'SELECT_QUESTION',
  GIVE_TESTIMONY: 'GIVE_TESTIMONY',
  ELIMINATE_SUSPECT: 'ELIMINATE_SUSPECT',
} as const;
