export const TESTEMUNHA_OCULAR_PHASES = {
  WITNESS_SELECTION: 'WITNESS_SELECTION',
  QUESTION_SELECTION: 'QUESTION_SELECTION',
  QUESTIONING: 'QUESTIONING',
  TRIAL: 'TRIAL',
  FINAL_TRIAL: 'FINAL_TRIAL',
} as const;

export const TESTEMUNHA_OCULAR_ACTIONS = {
  SELECT_WITNESS: 'SELECT_WITNESS',
  SELECT_QUESTION: 'SELECT_QUESTION',
  GIVE_TESTIMONY: 'GIVE_TESTIMONY',
  ELIMINATE_SUSPECT: 'ELIMINATE_SUSPECT',
  FINAL_ELIMINATION: 'FINAL_ELIMINATION',
} as const;

export const OUTCOME = {
  CONTINUE: 'CONTINUE',
  WIN: 'WIN',
  LOSE: 'LOSE',
  FINAL_SHOWDOWN: 'FINAL_SHOWDOWN',
} as const;
