export const CRIMES_HEDIONDOS_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  CRIME_SELECTION: 'CRIME_SELECTION',
  SCENE_MARKING: 'SCENE_MARKING',
  GUESSING: 'GUESSING',
  REVEAL: 'REVEAL',
  GAME_OVER: 'GAME_OVER',
};

export const PLAYER_COUNT = {
  MIN: 3,
  MAX: 10,
};

export const TOTAL_ROUNDS = 6;
export const SCENE_TILES = 6;
