export const CRIMES_HEDIONDOS_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  CRIME_SELECTION: 'CRIME_SELECTION',
  SCENE_MARKING: 'SCENE_MARKING',
  GUESSING: 'GUESSING',
  REVEAL: 'REVEAL',
  GAME_OVER: 'GAME_OVER',
};

export const CRIMES_HEDIONDOS_ACTIONS = {
  SUBMIT_CRIME: 'SUBMIT_CRIME',
  SUBMIT_MARK: 'SUBMIT_MARK',
  SUBMIT_GUESSES: 'SUBMIT_GUESSES',
};

export const CRIMES_HEDIONDOS_ACHIEVEMENTS = {
  MOST_WRONG_GROUPS: 'MOST_WRONG_GROUPS',
  MOST_WRONG_GUESSES: 'MOST_WRONG_GUESSES',
  MOST_ONE_GUESSES: 'MOST_ONE_GUESSES',
  MOST_TWO_GUESSES: 'MOST_TWO_GUESSES',
  MOST_THREE_GUESSES: 'MOST_THREE_GUESSES',
  MOST_CORRECT_GUESSES: 'MOST_CORRECT_GUESSES',
  EARLIEST_CORRECT_GUESS: 'EARLIEST_CORRECT_GUESS',
  LATEST_CORRECT_GUESS: 'LATEST_CORRECT_GUESS',
  MOST_SELECTED_WEAPONS: 'MOST_SELECTED_WEAPONS',
  FEWEST_SELECTED_WEAPONS: 'FEWEST_SELECTED_WEAPONS',
  MOST_SELECTED_EVIDENCE: 'MOST_SELECTED_EVIDENCE',
  FEWEST_SELECTED_EVIDENCE: 'FEWEST_SELECTED_EVIDENCE',
};

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 10,
};

export const TOTAL_ROUNDS = 7;
export const SCENE_TILES_COUNT = 6;

export const CARDS_PER_GAME = 16;

export const ITEMS_GROUP_COUNT = 4;
export const ITEMS_PER_GROUP = 4;

export const GUESS_STATUS = {
  LOCKED: 'LOCKED',
  CORRECT: 'CORRECT',
  ONE: 'ONE',
  TWO: 'TWO',
  THREE: 'THREE',
  WRONG_GROUP: 'WRONG_GROUP',
  WRONG: 'WRONG',
};
