export const CONTADORES_HISTORIAS_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  STORY: 'STORY',
  CARD_PLAY: 'CARD_PLAY',
  VOTING: 'VOTING',
  RESOLUTION: 'RESOLUTION',
  GAME_OVER: 'GAME_OVER',
};

export const CONTADORES_HISTORIAS_ACTIONS = {
  SUBMIT_STORY: 'SUBMIT_STORY',
  PLAY_CARD: 'PLAY_CARD',
  SUBMIT_VOTE: 'SUBMIT_VOTE',
};

export const PLAYER_COUNTS = {
  MIN: 3,
  MAX: 10,
};

export const CONTADORES_HISTORIAS_ACHIEVEMENTS = {
  MOST_DECEIVING: 'MOST_DECEIVING',
  WORST_CARDS: 'WORST_CARDS',
  WORST_CLUES: 'WORST_CLUES',
  EASIEST_CLUES: 'EASIEST_CLUES',
  HARDEST_CLUES: 'HARDEST_CLUES',
  TABLE_VOTES: 'TABLE_VOTES',
};

export const CARDS_PER_PLAYER = 30;

export const HAND_LIMIT = 10;

export const MAX_ROUNDS = 10;

export const GAME_OVER_SCORE_THRESHOLD = 20;

export const TABLE_CARDS_BY_PLAYER_COUNT = {
  3: 3,
  4: 2,
  5: 2,
  6: 1,
  7: 1,
  8: 0,
  9: 0,
  10: 0,
};

export const OUTCOME = {
  NORMAL: 'NORMAL',
  EVERYBODY_GOT: 'EVERYBODY_GOT',
  NOBODY_GOT: 'NOBODY_GOT',
};
