export const FOFOCA_QUENTE_PHASES = {
  LOBBY: 'LOBBY',
  RULES: 'RULES',
  SETUP: 'SETUP',
  ROLES_SELECTION: 'ROLES_SELECTION',
  BOARD_SETUP: 'BOARD_SETUP',
  INTIMIDATION: 'INTIMIDATION',
  RUMOR: 'RUMOR',
  RESPONSE: 'RESPONSE',
  INVESTIGATION: 'INVESTIGATION',
  SCHOOL: 'SCHOOL',
  RESOLUTION: 'RESOLUTION',
  GAME_OVER: 'GAME_OVER',
};

export const FOFOCA_QUENTE_ACTIONS = {
  SUBMIT_PLAYERS_ROLES: 'SUBMIT_PLAYERS_ROLES',
  SUBMIT_SOCIAL_GROUP: 'SUBMIT_SOCIAL_GROUP',
  SUBMIT_INTIMIDATION: 'SUBMIT_INTIMIDATION',
  SUBMIT_RUMOR: 'SUBMIT_RUMOR',
  SUBMIT_SKIP_RUMOR: 'SUBMIT_SKIP_RUMOR',
  SUBMIT_RESPONSE: 'SUBMIT_RESPONSE',
  UPDATE_DETECTIVE_POSITION: 'UPDATE_DETECTIVE_POSITION',
  UPDATE_STUDENT_POSITION: 'MOVE_STUDENTS',
  // TODO: do I need more specific?
  SUBMIT_INVESTIGATION: 'SUBMIT_INVESTIGATION',
};

export const FOFOCA_QUENTE_ACHIEVEMENTS = {
  PLAYED_AS_GOSSIPER: 'PLAYED_AS_GOSSIPER',
  PLAYED_AS_DETECTIVE: 'PLAYED_AS_DETECTIVE',
  WON_AS_GOSSIPER: 'WON_AS_GOSSIPER',
  WON_AS_DETECTIVE: 'WON_AS_DETECTIVE',
};

export const PLAYER_COUNTS = {
  MIN: 2,
  MAX: 2,
};

export const MAX_ROUNDS = 6;

export const TOTAL_STUDENTS = 20;

export const TOTAL_RUMORS = 10;

export const TOTAL_MOTIVATIONS = 6;

export const STARTING_STUDENT_POSITIONS = [
  0, 0, 1, 2, 3, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 12, 13, 14, 15, 15,
];
